'use strict';
(() => {
const $=id=>document.getElementById(id), canvas=$('world'), start=$('start');
if(!window.BABYLON){$('error').textContent='3D 엔진을 불러오지 못했습니다. 페이지를 새로고침해 주세요.';start.textContent='연결 실패';return}
const B=BABYLON,V=B.Vector3,C=B.Color3;let touch=matchMedia('(pointer:coarse)').matches;
let engine,scene;
try{engine=new B.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:false,powerPreference:'high-performance'});scene=new B.Scene(engine)}catch(e){$('error').textContent='이 브라우저에서 3D 화면을 시작할 수 없습니다. Safari 또는 Chrome에서 게임 링크를 열어 주세요.';return}
engine.setHardwareScalingLevel(Math.max(1,(window.devicePixelRatio||1)/(touch?1.25:1.65)));
scene.clearColor=new B.Color4(.045,.085,.09,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.024;scene.fogColor=new C(.08,.15,.16);scene.skipPointerMovePicking=true;
const camera=new B.FreeCamera('eyes',new V(-7,3.5,-19),scene);camera.minZ=.06;camera.maxZ=110;camera.fov=1.18;camera.rotation=new V(.03,.34,0);scene.activeCamera=camera;
const hemi=new B.HemisphericLight('sky',new V(0,1,0),scene);hemi.intensity=.72;hemi.diffuse=new C(.58,.74,.77);hemi.groundColor=new C(.17,.23,.2);
const moon=new B.DirectionalLight('moon',new V(-.35,-1,.35),scene);moon.intensity=.8;moon.diffuse=new C(.7,.86,.84);moon.position=new V(10,30,-20);
const shadow=new B.ShadowGenerator(touch?512:1024,moon);shadow.usePercentageCloserFiltering=!touch;shadow.bias=.003;
const mats={};function mat(name,hex,emission=0){const m=new B.StandardMaterial(name,scene);m.diffuseColor=C.FromHexString(hex);m.specularColor=new C(.08,.09,.08);if(emission)m.emissiveColor=m.diffuseColor.scale(emission);m.freeze();mats[name]=m;return m}
const concrete=mat('concrete','#364548'),steel=mat('steel','#263236'),dark=mat('dark','#111b20'),rust=mat('rust','#534735'),trim=mat('trim','#94a29b'),yellow=mat('yellow','#b9a960'),green=mat('green','#c2f96a',.7),red=mat('red','#fe5935',1),skin=mat('skin','#929481'),cloth=mat('cloth','#445453'),pants=mat('pants','#222c32'),eyes=mat('eyes','#fbd274',1.6),white=mat('white','#ccd5b6',.1);
const obstacles=[],hits=[],enemies=[],particles=[],supplies=[];
function box(name,x,y,z,w,h,d,m,solid=false){const mesh=B.MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);mesh.position.set(x,y,z);mesh.material=m;mesh.receiveShadows=true;mesh.isPickable=solid;if(solid){obstacles.push({x,z,w:w/2,d:d/2});hits.push(mesh);shadow.addShadowCaster(mesh)}return mesh}
function label(text,x,y,z,w=4,h=1,color='#d5f568',rotation=0){const tex=new B.DynamicTexture('sign-'+text,{width:512,height:128},scene,false);tex.hasAlpha=true;const c=tex.getContext();c.clearRect(0,0,512,128);c.fillStyle=color;c.font='bold 60px Arial';c.textAlign='center';c.fillText(text,256,85);tex.update();const m=new B.StandardMaterial('sign',scene);m.diffuseTexture=tex;m.emissiveTexture=tex;m.opacityTexture=tex;m.disableLighting=true;m.backFaceCulling=false;const p=B.MeshBuilder.CreatePlane('label',{width:w,height:h},scene);p.position.set(x,y,z);p.rotation.y=rotation;p.material=m;p.isPickable=false;return p}
const floor=box('wet asphalt',0,-.2,2,44,.4,58,mat('asphalt','#243135'));floor.receiveShadows=true;floor.isPickable=true;hits.push(floor);
box('west wall',-22,3,2,1,6,58,concrete,true);box('east wall',22,3,2,1,6,58,concrete,true);box('back wall',0,3,-27,44,6,1,concrete,true);box('north left',-14,4,30,16,8,1,concrete,true);box('north right',14,4,30,16,8,1,concrete,true);box('gate',0,3,29.7,12,6,.5,dark,true);
for(let side of [-1,1])for(let z=-22;z<28;z+=8){box('buttress',side*21,2.8,z,.7,5.6,1,steel);box('window frame',side*21.43,3.8,z+3,.07,1.4,2,trim);box('window black',side*21.36,3.8,z+3,.1,1.2,1.8,dark)}
for(let x=-30;x<=30;x+=9){const height=12+Math.abs(Math.sin(x))*16;box('skyline',x,height/2,40,8,height,8,mat('tower'+x,x%2?'#192b31':'#203339'));for(let y=6;y<height;y+=4)for(let k=-2;k<=2;k+=2)box('distant window',x+k,y,35.94,.7,1.1,.05,Math.random()>.65?yellow:dark)}
// Cover leaves wide, connected routes through the yard.
box('cargo A',-11,1.6,-3,7,3.2,10,mat('cargo','#5d6658'),true);box('cargo B',12,1.6,9,8,3.2,10,mat('cargoB','#465a5b'),true);
for(let z=-7;z<2;z+=.7)box('cargo ribs',-7.46,1.6,z,.1,3,.09,steel);
for(let z=5;z<14;z+=.7)box('cargo ribs',7.95,1.6,z,.1,3,.09,steel);
box('roadblock',2,.65,1,5,1.3,1.6,concrete,true);box('roadblock2',-10,.65,16,6,1.3,1.6,concrete,true);
for(let x=0;x<4;x++)box('hazard stripe',.4+x,.9,.17,.32,.35,.04,yellow).rotation.z=-.5;
for(const [x,z] of [[16,-15],[-16,9],[5,18]]){box('crate',x,.65,z,1.5,1.3,1.5,rust,true);box('crate band',x,.7,z+.76,1.5,.1,.03,trim)}
for(let z=-22;z<27;z+=5){box('lane mark',0,.015,z,.12,.02,2,yellow);box('drain',-19,.01,z,1,.02,.4,steel)}
function lamp(x,z,color){box('lamp pole',x,3,z,.12,6,.12,steel);box('lamp arm',x-Math.sign(x)*1,5.9,z,2,.12,.1,steel);box('lamp bulb',x-Math.sign(x)*2,5.78,z,.5,.09,.5,color==='red'?red:white);const l=new B.PointLight('yard lamp',new V(x-Math.sign(x)*2,5.2,z),scene);l.diffuse=color==='red'?new C(1,.24,.1):new C(.65,.86,.69);l.intensity=color==='red'?8:5;l.range=14}
lamp(-19,-12,'white');lamp(19,18,'red');lamp(-19,22,'white');
label('QUARANTINE',0,6.4,29.35,10,1.8,'#aab9ad');label('09',-11,2.1,-8.06,2,1,'#cad2b5');label('NO ENTRY',0,2.6,-26.4,5,1,'#d89270',Math.PI);
box('evac overhead',0,4.8,24,9,.18,.18,steel);box('evac post',-4.5,2.4,24,.18,4.8,.18,steel);box('evac post',4.5,2.4,24,.18,4.8,.18,steel);label('EVAC / 09',0,4.25,23.9,4.5,.8);
const evac=B.MeshBuilder.CreateTorus('extraction',{diameter:5,thickness:.07,tessellation:40},scene);evac.position.set(0,.06,25);evac.material=green;evac.isPickable=false;evac.setEnabled(false);
const beacon=new B.PointLight('extraction light',new V(0,2,25),scene);beacon.diffuse=new C(.45,1,.1);beacon.intensity=0;beacon.range=10;
for(const [x,z] of [[-17,-18],[17,1],[-17,21]]){const root=new B.TransformNode('ammo supply',scene);const b=box('ammo box',x,.4,z,1,.7,.7,green);b.parent=root;const light=box('ammo band',x,.77,z,.6,.03,.35,dark);light.parent=root;label('AMMO',x,1.3,z,1.6,.4);supplies.push({x,z,root,taken:false})}
// First-person weapon is real geometry, rendered over the world.
const gun=new B.TransformNode('carbine',scene);gun.parent=camera;gun.position.set(.24,-.24,.5);
function gunBox(name,x,y,z,w,h,d,m){const g=box(name,x,y,z,w,h,d,m);g.parent=gun;g.renderingGroupId=1;return g}
gunBox('receiver',0,0,.1,.13,.14,.42,dark);gunBox('upper rail',0,.084,.12,.09,.025,.4,steel);gunBox('handguard',0,.015,.42,.11,.12,.28,steel);gunBox('barrel',0,.025,.64,.045,.045,.24,dark);gunBox('front sight',0,.1,.48,.022,.07,.025,trim);gunBox('sight L',-.032,.1,-.02,.018,.06,.022,trim);gunBox('sight R',.032,.1,-.02,.018,.06,.022,trim);gunBox('magazine',0,-.12,.1,.09,.2,.12,steel);gunBox('stock',0,-.02,-.22,.09,.11,.25,dark);gunBox('gloved hand',.025,-.12,-.12,.13,.13,.13,cloth);gunBox('left glove',-.05,-.085,.39,.12,.13,.15,cloth);
const muzzle=B.MeshBuilder.CreateSphere('muzzle',{diameter:.17,segments:5},scene);muzzle.parent=gun;muzzle.position.set(0,.025,.79);muzzle.material=mat('flash','#ffe7a0',2);muzzle.renderingGroupId=1;muzzle.isPickable=false;muzzle.setEnabled(false);
const flash=new B.PointLight('flash',new V(0,0,0),scene);flash.parent=camera;flash.position.z=1;flash.diffuse=new C(1,.7,.3);flash.intensity=0;flash.range=8;gun.setEnabled(false);
let state='ready',hp=100,ammo=30,reserve=150,kits=1,kills=0,wave=0,quota=0,spawned=0,spawnClock=0,intermission=0,extraction=false,clock=0,shotClock=0,reloading=0,recoil=0,damage=0,hitTime=0,noticeTime=0,healTime=0,held=false,yaw=0,pitch=0,step=0,gameTime=0;
const key=new Set(),move={x:0,y:0};let audio=null,soundOn=true,dragLook=null;const touchIds={stick:null,look:null,fire:null};
function beep(freq,duration,volume=.08,type='sine'){if(!audio||!soundOn)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*.35),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function shotSound(){if(!audio||!soundOn)return;const n=audio.createBuffer(1,audio.sampleRate*.12,audio.sampleRate),data=n.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,3);const s=audio.createBufferSource(),g=audio.createGain(),f=audio.createBiquadFilter();s.buffer=n;f.type='lowpass';f.frequency.value=1700;g.gain.value=.28;s.connect(f);f.connect(g);g.connect(audio.destination);s.start();beep(95,.1,.14,'triangle')}
function audioStart(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{})}catch{}}
function inputMode(){document.body.classList.toggle('touch-mode',touch);$('inputmode').textContent=touch?'터치 조작':'마우스 조작'}
inputMode();$('inputmode').onclick=()=>{touch=!touch;clearInput();inputMode()};
$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='사운드 '+(soundOn?'ON':'OFF');if(soundOn)audioStart()};
function notify(s,t=3){$('notice').textContent=s;noticeTime=t}
function ui(){ $('health').textContent=Math.ceil(hp);$('healthbar').style.width=Math.max(0,hp)+'%';$('healthbar').style.background=hp<30?'#f47752':'#d5f568';$('ammo').textContent=ammo;$('reserve').textContent=reserve;$('kits').textContent=kits;$('kills').textContent=kills+' KILLS';$('remaining').textContent=extraction?'북쪽 녹색 원으로 이동':intermission>0?'다음 습격까지 '+Math.ceil(intermission)+'초':Math.max(0,quota-spawned+enemies.length)+'명 남음';$('phase').textContent=extraction?'EXTRACTION OPEN':'WAVE '+String(wave).padStart(2,'0')+' / 03';$('reloadstatus').textContent=reloading>0?'재장전 중…':ammo===0?'R / 재장전':'5.56 × 45 MM';}
function clearInput(){key.clear();held=false;move.x=move.y=0;dragLook=null;touchIds.stick=touchIds.look=touchIds.fire=null;$('knob').style.transform='translate(0,0)'}
function lock(){if(touch)return;try{const p=canvas.requestPointerLock?.();if(p?.catch)p.catch(()=>notify('마우스를 누른 채 움직여 조준할 수도 있어요',4))}catch{notify('마우스 드래그로 조준하세요',3)}}
function waveStart(){wave++;quota=[0,8,14,20][wave];spawned=0;spawnClock=1;intermission=0;notify('WAVE '+wave+' — '+(wave===3?'마지막 습격. 버텨내세요.':'감염자 접근 중'),3.5);beep(160,.7,.1,'sawtooth');ui()}
function begin(){for(const e of enemies)e.root.dispose();enemies.length=0;for(const p of particles)p.mesh.dispose();particles.length=0;for(const s of supplies){s.taken=false;s.root.setEnabled(true)}hp=100;ammo=30;reserve=150;kits=1;kills=wave=0;clock=gameTime=0;reloading=shotClock=recoil=damage=hitTime=0;extraction=false;evac.setEnabled(false);beacon.intensity=0;camera.position.set(0,1.65,-19);yaw=pitch=0;camera.rotation.set(0,0,0);clearInput();state='playing';$('screen').hidden=true;$('hud').hidden=false;$('touch').hidden=!touch;gun.setEnabled(true);audioStart();waveStart();lock();ui()}
function pause(){if(state!=='playing')return;state='paused';clearInput();if(document.pointerLockElement)document.exitPointerLock();$('touch').hidden=true;$('screen').hidden=false;$('screen-title').textContent='잠시 숨을 고르세요.';$('screen-desc').textContent='이어하기를 누르면 같은 지점에서 계속합니다.';start.textContent='계속 생존하기 →'}
function resume(){state='playing';$('screen').hidden=true;$('touch').hidden=!touch;clearInput();audioStart();lock()}
function end(won){state=won?'won':'lost';clearInput();if(document.pointerLockElement)document.exitPointerLock();$('touch').hidden=true;$('screen').hidden=false;$('screen-title').textContent=won?'탈출 성공. 신호가 이어졌다.':'교신 두절. 생존자 응답 없음.';$('screen-desc').textContent=`${kills}명 처치 · ${Math.floor(gameTime)}초 생존 · ${wave}/3 단계. ${won?'격리구역을 빠져나왔습니다.':'엄폐물을 돌아 이동하며 거리를 확보하세요.'}`;start.textContent='다시 투입하기 →';beep(won?680:100,.6,.12)}
start.onclick=()=>state==='paused'?resume():begin();$('pause').onclick=pause;
function blocked(x,z,r=.38){if(x<-20.8+r||x>20.8-r||z<-25.5+r||z>28.6-r)return true;return obstacles.some(o=>Math.abs(x-o.x)<o.w+r&&Math.abs(z-o.z)<o.d+r)}
function advance(pos,dx,dz,r){if(!blocked(pos.x+dx,pos.z,r))pos.x+=dx;if(!blocked(pos.x,pos.z+dz,r))pos.z+=dz}
// Grid flow field routes the horde around containers and concrete barriers.
const gridSize=1.25,cols=34,rows=44,originX=-21,originZ=-26;let field=new Int16Array(cols*rows),flowClock=0;
function cell(x,z){return {x:Math.max(0,Math.min(cols-1,Math.floor((x-originX)/gridSize))),z:Math.max(0,Math.min(rows-1,Math.floor((z-originZ)/gridSize)))}}
const nav=new Uint8Array(cols*rows);for(let z=0;z<rows;z++)for(let x=0;x<cols;x++)nav[z*cols+x]=blocked(originX+(x+.5)*gridSize,originZ+(z+.5)*gridSize,.42)?1:0;
function flow(){field.fill(-1);const p=cell(camera.position.x,camera.position.z),first=p.z*cols+p.x,q=[first];field[first]=0;for(let i=0;i<q.length;i++){const n=q[i],x=n%cols,z=Math.floor(n/cols);for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,zz=z+dz,j=zz*cols+xx;if(xx<0||xx>=cols||zz<0||zz>=rows||nav[j]||field[j]>=0)continue;field[j]=field[n]+1;q.push(j)}}}
function spawnEnemy(){let x,z;for(let tries=0;tries<30;tries++){x=(Math.random()-.5)*38;z=Math.random()>.4?25:(Math.random()-.5)*42;if(!blocked(x,z,.7)&&Math.hypot(x-camera.position.x,z-camera.position.z)>12)break}if(blocked(x,z,.7)||Math.hypot(x-camera.position.x,z-camera.position.z)<8){x=18;z=25}
const root=new B.TransformNode('infected',scene);root.position.set(x,0,z);const runner=wave>1&&Math.random()<.3,e={root,hp:runner?80:110,speed:runner?2.7:1.25+wave*.19,attack:0,phase:Math.random()*6,limbs:[],runner};
function part(name,x,y,z,w,h,d,m){const mesh=box(name,x,y,z,w,h,d,m);mesh.parent=root;mesh.isPickable=true;mesh.metadata={enemy:e,head:name==='head'};shadow.addShadowCaster(mesh);return mesh}
part('torso',0,1.08,0,.5,.68,.29,runner?rust:cloth);part('head',0,1.64,.055,.3,.36,.29,skin);part('eye',-.09,1.69,.207,.048,.04,.02,eyes);part('eye',.09,1.69,.207,.048,.04,.02,eyes);
for(const side of [-1,1]){const leg=part('leg',side*.14,.42,0,.18,.72,.2,pants);e.limbs.push(leg);const arm=part('arm',side*.34,1.08,.18,.16,.62,.18,skin);arm.rotation.x=-.75;e.limbs.push(arm)}root.rotation.z=(Math.random()-.5)*.1;enemies.push(e);spawned++}
function sparks(point,color,count=6){for(let i=0;i<count;i++){const m=B.MeshBuilder.CreateBox('impact',{size:.06+Math.random()*.04},scene);m.position.copyFrom(point);m.material=color;m.isPickable=false;particles.push({mesh:m,v:new V((Math.random()-.5)*2,Math.random()*2,(Math.random()-.5)*2),life:.35+Math.random()*.25})}}
function reload(){if(state!=='playing'||reloading||ammo===30||reserve<=0)return;reloading=1.7;held=false;beep(340,.09,.06,'square');notify('재장전',1.5);ui()}
function heal(){if(state!=='playing')return;if(kits<1){notify('구급팩이 없습니다',1.5);return}if(hp>=100){notify('체력이 가득 찼습니다',1.5);return}kits--;hp=Math.min(100,hp+60);healTime=.3;beep(600,.25,.08);notify('체력 +60',2);ui()}
function shoot(){if(state!=='playing'||shotClock>0||reloading)return;if(ammo<=0){reload();if(reserve===0){shotClock=.35;beep(80,.04,.06,'square');notify('보급 상자에 접근해 탄약을 확보하세요',2)}return}ammo--;shotClock=.115;recoil=.07;muzzle.setEnabled(true);flash.intensity=14;shotSound();const ray=camera.getForwardRay(65),pick=scene.pickWithRay(ray,m=>m.isPickable===true);if(pick?.hit){const e=pick.pickedMesh.metadata?.enemy;if(e&&e.hp>0){const head=pick.pickedMesh.metadata.head;e.hp-=head?115:40;hitTime=.13;$('hitmarker').style.color=head?'#ffb45d':'#d5f568';sparks(pick.pickedPoint,head?yellow:rust,5);if(e.hp<=0){kills++;e.root.dispose();enemies.splice(enemies.indexOf(e),1);if(head)notify('HEADSHOT',.7)}}else sparks(pick.pickedPoint,trim,3)}ui()}
$('reload').onclick=reload;$('heal').onclick=heal;
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;key.add(e.code);if(e.code==='KeyR')reload();if(e.code==='KeyE')heal();if(e.code==='Escape')pause()});addEventListener('keyup',e=>key.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||touch||e.button!==0)return;held=true;dragLook={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);if(!document.pointerLockElement)lock()});
addEventListener('pointerup',()=>{if(!touch){held=false;dragLook=null}});canvas.addEventListener('pointercancel',()=>{held=false;dragLook=null});canvas.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('mousemove',e=>{if(state!=='playing'||touch)return;if(document.pointerLockElement===canvas){yaw+=e.movementX*.0023;pitch+=e.movementY*.0023}else if(dragLook){yaw+=(e.clientX-dragLook.x)*.004;pitch+=(e.clientY-dragLook.y)*.004;dragLook.x=e.clientX;dragLook.y=e.clientY}pitch=Math.max(-1.25,Math.min(1.25,pitch))});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing'&&!touch)pause()});addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function pad(node,type,down,moveFn,up){node.addEventListener('pointerdown',e=>{if(state!=='playing'||touchIds[type]!==null)return;e.preventDefault();touchIds[type]=e.pointerId;node.setPointerCapture(e.pointerId);down(e)});node.addEventListener('pointermove',e=>{if(touchIds[type]===e.pointerId)moveFn(e)});for(const name of ['pointerup','pointercancel','lostpointercapture'])node.addEventListener(name,e=>{if(touchIds[type]!==e.pointerId)return;touchIds[type]=null;up()})}
let stickOrigin={x:0,y:0},lookOrigin={x:0,y:0};
function stickMove(e){let x=e.clientX-stickOrigin.x,y=e.clientY-stickOrigin.y,len=Math.hypot(x,y),scale=len>38?38/len:1;x*=scale;y*=scale;move.x=x/38;move.y=y/38;$('knob').style.transform=`translate(${x}px,${y}px)`}
pad($('stick'),'stick',e=>{const r=$('stick').getBoundingClientRect();stickOrigin={x:r.left+r.width/2,y:r.top+r.height/2};stickMove(e)},stickMove,()=>{move.x=move.y=0;$('knob').style.transform='translate(0,0)'});
pad($('look'),'look',e=>{lookOrigin={x:e.clientX,y:e.clientY}},e=>{yaw+=(e.clientX-lookOrigin.x)*.005;pitch+=(e.clientY-lookOrigin.y)*.005;pitch=Math.max(-1.25,Math.min(1.25,pitch));lookOrigin={x:e.clientX,y:e.clientY}},()=>{});
pad($('fire'),'fire',()=>{held=true;shoot()},()=>{},()=>{held=false});
function tick(dt){clock+=dt;if(state==='ready'){camera.rotation.y=.34+Math.sin(clock*.09)*.08;return}if(state!=='playing')return;gameTime+=dt;shotClock=Math.max(0,shotClock-dt);recoil=Math.max(0,recoil-dt*.6);damage=Math.max(0,damage-dt*1.7);hitTime=Math.max(0,hitTime-dt);noticeTime-=dt;if(noticeTime<=0)$('notice').textContent='';$('damage').style.opacity=damage;$('hitmarker').style.opacity=hitTime>0?1:0;muzzle.setEnabled(shotClock>.075);flash.intensity=shotClock>.075?14:0;
if(reloading>0){reloading-=dt;if(reloading<=0){reloading=0;const amount=Math.min(30-ammo,reserve);ammo+=amount;reserve-=amount;beep(450,.07,.06,'square');ui()}}
if(held)shoot();let mx=(key.has('KeyD')?1:0)-(key.has('KeyA')?1:0)+move.x,mz=(key.has('KeyW')?1:0)-(key.has('KeyS')?1:0)-move.y,len=Math.hypot(mx,mz);if(len>1){mx/=len;mz/=len}const speed=key.has('ShiftLeft')?6.1:4.6;advance(camera.position,(mx*Math.cos(yaw)+mz*Math.sin(yaw))*speed*dt,(-mx*Math.sin(yaw)+mz*Math.cos(yaw))*speed*dt,.38);if(len>.1)step+=dt*10;camera.position.y=1.65+(len>.1?Math.sin(step)*.027:0);camera.rotation.set(pitch-recoil*.22,yaw,0);gun.position.y=-.24+(len>.1?Math.sin(step)*.012:0)-(reloading>0?.2:0);gun.position.z=.5-recoil;gun.rotation.x=reloading>0?-.5:0;
flowClock-=dt;if(flowClock<=0){flow();flowClock=.5}
if(!extraction&&intermission<=0&&spawned<quota&&enemies.length<12){spawnClock-=dt;if(spawnClock<=0){spawnEnemy();spawnClock=.8+Math.random()*.6;ui()}}
for(const e of enemies){const p=e.root.position,dx=camera.position.x-p.x,dz=camera.position.z-p.z,distance=Math.hypot(dx,dz);e.attack-=dt;e.phase+=dt*e.speed*5;e.root.rotation.y=Math.atan2(dx,dz);e.root.position.y=Math.sin(e.phase)*.028;e.limbs[0].rotation.x=Math.sin(e.phase)*.45;e.limbs[2].rotation.x=-Math.sin(e.phase)*.45;e.limbs[1].rotation.x=-.75-Math.sin(e.phase)*.12;e.limbs[3].rotation.x=-.75+Math.sin(e.phase)*.12;
if(distance>1.1){let tx=dx,tz=dz;const ray=new B.Ray(new V(p.x,1,p.z),new V(dx,0,dz).normalize(),distance);const wall=scene.pickWithRay(ray,m=>hits.includes(m));if(wall?.hit){const c=cell(p.x,p.z);let min=field[c.z*cols+c.x];if(min<0)min=32767;for(const [xx,zz] of [[c.x+1,c.z],[c.x-1,c.z],[c.x,c.z+1],[c.x,c.z-1]]){if(xx<0||xx>=cols||zz<0||zz>=rows)continue;const f=field[zz*cols+xx];if(f>=0&&f<min){min=f;tx=originX+(xx+.5)*gridSize-p.x;tz=originZ+(zz+.5)*gridSize-p.z}}}let l=Math.hypot(tx,tz)||1;let vx=tx/l,vz=tz/l;for(const other of enemies){if(e===other)continue;const ox=p.x-other.root.position.x,oz=p.z-other.root.position.z,dd=Math.hypot(ox,oz);if(dd<.85&&dd>.01){vx+=ox/dd*(.85-dd)*1.5;vz+=oz/dd*(.85-dd)*1.5}}advance(p,vx*e.speed*dt,vz*e.speed*dt,.35)}else if(e.attack<=0){hp=Math.max(0,hp-(e.runner?8:12));damage=.8;e.attack=1;beep(65,.12,.13,'sawtooth');ui();if(hp<=0){end(false);break}}}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=dt*5;p.mesh.position.addInPlace(p.v.scale(dt));if(p.life<=0){p.mesh.dispose();particles.splice(i,1)}}
for(const s of supplies)if(!s.taken&&Math.hypot(camera.position.x-s.x,camera.position.z-s.z)<1.7){s.taken=true;s.root.setEnabled(false);reserve+=90;notify('탄약 보급 +90',2);beep(700,.15,.08);ui()}
if(!extraction&&spawned>=quota&&enemies.length===0&&intermission<=0){if(wave===3){extraction=true;evac.setEnabled(true);beacon.intensity=10;$('mission').textContent='북쪽 EVAC 표지 아래 녹색 원으로 이동';notify('구역 확보. 북쪽 탈출 지점으로 이동하세요.',5);ui()}else{intermission=7;reserve+=60;hp=Math.min(100,hp+15);notify('습격 종료 · 탄약 +60 / 체력 +15',3);ui()}}
if(intermission>0){intermission-=dt;if(intermission<=0)waveStart();else ui()}
if(extraction){evac.rotation.y+=dt;beacon.intensity=8+Math.sin(clock*3)*2;if(Math.hypot(camera.position.x,camera.position.z-25)<2.4)end(true)}
}
let last=performance.now();engine.runRenderLoop(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.04);last=now;try{tick(dt);scene.render()}catch(e){console.error(e);pause();$('error').textContent='실행 오류가 발생했습니다. 새로고침 후 다시 시도해 주세요.';engine.stopRenderLoop()}});
addEventListener('resize',()=>{engine.resize();clearInput()});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('error').textContent='3D 화면 연결이 끊겼습니다. 새로고침해 주세요.'});
scene.executeWhenReady(()=>{start.disabled=false;start.textContent='격리구역 진입 →'});
// Expose only actions already available in the game interface.
if(navigator.modelContext?.registerTool||document.modelContext?.registerTool){const context=navigator.modelContext||document.modelContext;for(const tool of [{name:'read_survival_status',title:'생존 상태 확인',description:'현재 게임의 체력, 탄약, 단계와 결과를 확인합니다.',annotations:{readOnlyHint:true},execute:()=>({state,hp,ammo,reserve,kills,wave,extraction})},{name:'pause_survival_game',title:'게임 일시정지',description:'진행 중인 게임을 일시정지합니다.',annotations:{readOnlyHint:false},execute:()=>{pause();return{state}}}]){try{Promise.resolve(context.registerTool({...tool,inputSchema:{type:'object',properties:{},additionalProperties:false},execute:input=>{if(input&&Object.keys(input).length)throw Error('입력 항목이 없습니다.');return tool.execute()}})).catch(()=>{})}catch{}}}
})();
