'use strict';
(() => {
const $=id=>document.getElementById(id),canvas=$('world'),start=$('start'),R=window.BattleRules,controls=window.GameControls,boot=window.GameBoot,W=window.BattleWorld;
function startupFailure(message,error){$('error').textContent=message;boot?.fail(message,error?.message||'')}
if(!window.BABYLON||!R||!controls||!window.createLootVisuals||!W){startupFailure('게임 파일을 불러오지 못했습니다. 페이지를 새로고침해 주세요.');return}
const B=BABYLON,V=B.Vector3,C=B.Color3;const mobileDevice=matchMedia('(pointer:coarse)').matches||(navigator.maxTouchPoints||0)>0;let fieldEnvironment=null;let touch=controls.isTouch(),highQuality=!mobileDevice&&!boot?.safe,engine,scene;
try{engine=new B.Engine(canvas,highQuality,{stencil:false,powerPreference:mobileDevice?'default':'high-performance'});scene=new B.Scene(engine)}catch(error){startupFailure('3D 화면을 시작할 수 없습니다. 실행 진단에서 3D 기능을 확인해 주세요.',error);return}
function quality(){const dpr=Math.min(window.devicePixelRatio||1,highQuality?(mobileDevice?1.25:2):1);scene.shadowsEnabled=highQuality;fieldEnvironment?.quality(highQuality);engine.setHardwareScalingLevel(1/dpr);$('quality').textContent=highQuality?'화질: 선명':'화질: 성능';engine.resize()}
quality();$('quality').onclick=()=>{highQuality=!highQuality;quality()};
scene.clearColor=new B.Color4(.54,.62,.67,1);scene.fogMode=B.Scene.FOGMODE_LINEAR;scene.fogStart=75;scene.fogEnd=220;scene.fogColor=new C(.62,.67,.68);scene.skipPointerMovePicking=true;
scene.imageProcessingConfiguration.toneMappingEnabled=true;scene.imageProcessingConfiguration.toneMappingType=B.ImageProcessingConfiguration.TONEMAPPING_ACES;scene.imageProcessingConfiguration.contrast=1.08;scene.imageProcessingConfiguration.exposure=1.15;
const camera=new B.FreeCamera('player',new V(-11,6,-61),scene);camera.minZ=.06;camera.maxZ=320;camera.fov=1.08;camera.rotation.set(.05,.28,0);scene.activeCamera=camera;
// `camera` stays the player's eye and keeps driving movement, aiming and every gameplay query.
// Third person only swaps which camera renders, so the authoritative shot ray never changes.
const viewCam=new B.FreeCamera('shoulder',new V(-11,6,-61),scene);viewCam.minZ=.06;viewCam.maxZ=320;viewCam.fov=1.08;
let thirdPerson=false,selfBody=null,netMoving=false;
const sky=new B.HemisphericLight('daylight',new V(0,1,0),scene);sky.intensity=.32;sky.diffuse=new C(.8,.87,1);sky.groundColor=new C(.19,.18,.15);
const sun=new B.DirectionalLight('sun',new V(-.6,-1,.4),scene);sun.position.set(40,65,-40);sun.intensity=2.1;sun.diffuse=new C(1,.91,.77);sun.autoCalcShadowZBounds=true;
const shadow=new B.ShadowGenerator(mobileDevice||boot?.safe?512:2048,sun);shadow.usePercentageCloserFiltering=true;shadow.filteringQuality=B.ShadowGenerator.QUALITY_LOW;shadow.bias=.0015;shadow.normalBias=.035;
function mat(name,hex,emission=0){const m=new B.StandardMaterial(name,scene);m.diffuseColor=C.FromHexString(hex);m.specularColor=new C(.08,.08,.08);if(emission)m.emissiveColor=m.diffuseColor.scale(emission);m.freeze();return m}
const M={grass:mat('grass','#7c925b'),road:mat('road','#737b7a'),concrete:mat('concrete','#c5c6b5'),cream:mat('plaster','#e7dfc4'),roof:mat('roof','#567c85'),dark:mat('gunmetal','#26333b'),steel:mat('steel','#637885'),wood:mat('wood','#a67c4d'),leaf:mat('leaf','#557b45'),leaf2:mat('leaf light','#769954'),bark:mat('bark','#806c4c'),yellow:mat('paint','#f2c660'),white:mat('white','#f0f1e3'),skin:mat('skin','#cda17f'),cloth:mat('enemy jacket','#bb7b4e'),pants:mat('enemy pants','#4b6056'),helmet:mat('helmet','#626e54'),glass:mat('glass','#456c7b'),ammo:mat('ammo','#dbb351',.15),med:mat('medical','#6bb4a2',.1),armor:mat('armor','#75bada',.1),purple:mat('rare','#b599d2',.15),flash:mat('muzzle','#ffe2a6',1.4)};
fieldEnvironment=window.createFieldEnvironment(B,scene,shadow,mobileDevice||boot?.safe);Object.assign(M,fieldEnvironment.materials);fieldEnvironment.quality(highQuality);
for(const [key,color,metal,rough]of [['dark','#353b40',.8,.36],['steel','#929b9d',.8,.43],['glass','#263b43',.65,.2]]){const m=new B.PBRMaterial(key,scene);m.albedoColor=C.FromHexString(color);m.metallic=metal;m.roughness=rough;M[key]=m}
const obstacles=[],staticHits=new Set(),enemies=[],loot=[],effects=[];
function box(name,x,y,z,w,h,d,m,solid=false,casts=true){const a=B.MeshBuilder.CreateBox(name,{width:w,height:h,depth:d},scene);a.position.set(x,y,z);a.material=m;fieldEnvironment.mapBox(a);a.receiveShadows=true;a.isPickable=solid;if(solid){obstacles.push({x,z,w:w/2,d:d/2});staticHits.add(a)}if(casts)shadow.addShadowCaster(a);return a}
function cylinder(name,x,y,z,d,h,m){const a=B.MeshBuilder.CreateCylinder(name,{diameter:d,height:h,tessellation:10},scene);a.position.set(x,y,z);a.material=m;a.isPickable=false;shadow.addShadowCaster(a);return a}
function label(text,x,y,z,w=4,h=1,color='#263b42',rotation=0){const t=new B.DynamicTexture('sign',{width:512,height:128},scene,false);t.hasAlpha=true;const c=t.getContext();c.clearRect(0,0,512,128);c.fillStyle=color;c.font='bold 56px Arial';c.textAlign='center';c.fillText(text,256,84);t.update();const m=new B.StandardMaterial('sign',scene);m.diffuseTexture=t;m.opacityTexture=t;m.emissiveColor=new C(.25,.25,.25);m.backFaceCulling=false;const a=B.MeshBuilder.CreatePlane('sign',{width:w,height:h},scene);a.position.set(x,y,z);a.rotation.y=rotation;a.material=m;a.isPickable=false;return a}
const floor=box('terrain',0,-.22,0,170,.4,170,M.grass,false,false);floor.isPickable=true;staticHits.add(floor);
box('north road',0,.002,0,10,.02,140,M.road,false,false);box('east road',0,.004,10,140,.02,9,M.road,false,false);
for(let z=-65;z<69;z+=8)box('lane paint',0,.018,z,.14,.018,3,M.yellow,false,false);
// Enterable structures: front doors and open interiors hold equipment.
function building(x,z,w=10,d=10){box('foundation',x,.02,z,w+.4,.05,d+.4,M.concrete,false,false);box('rear wall',x,1.8,z+d/2,w,3.6,.35,M.cream,true);box('left wall',x-w/2,1.8,z,.35,3.6,d,M.cream,true);box('right wall',x+w/2,1.8,z,.35,3.6,d,M.cream,true);const piece=(w-3.6)/2;box('front left',x-(1.8+piece/2),1.8,z-d/2,piece,3.6,.35,M.cream,true);box('front right',x+(1.8+piece/2),1.8,z-d/2,piece,3.6,.35,M.cream,true);box('door lintel',x,3.3,z-d/2,3.6,.6,.35,M.cream,false);const roof=box('flat roof',x,3.75,z,w+1,.28,d+1,M.roof,false);roof.isPickable=true;staticHits.add(roof);for(const side of [-1,1]){box('window',x+side*w*.3,2,z-d/2-.2,1.6,1.25,.025,M.glass,false,false);box('window sill',x+side*w*.3,1.32,z-d/2-.25,1.9,.15,.2,M.concrete)}for(const side of [-1,1]){const wx=x+side*w*.3;for(const dx of [-.85,.85])box('window frame',wx+dx,2,z-d/2-.24,.065,1.36,.09,M.steel,false,false);for(const yy of [1.35,2.65])box('window frame',wx,yy,z-d/2-.24,1.76,.06,.09,M.steel,false,false);box('window mullion',wx,2,z-d/2-.26,.055,1.3,.04,M.steel,false,false);box('concrete footing',x+side*(w/2-.08),.22,z,.46,.42,d,M.concrete,false,false)}
box('roof fascia',x,3.72,z-d/2-.5,w+1,.2,.12,M.steel,false,false);
for(const side of [-1,1]){const pipe=cylinder('drain pipe',x+side*(w/2+.13),1.8,z-d/2+.35,.11,3.6,M.steel);pipe.isPickable=false}
box('door frame top',x,3.02,z-d/2-.2,3.75,.12,.14,M.steel,false,false);
for(const side of [-1,1])box('door frame',x+side*1.83,1.5,z-d/2-.2,.09,3,.14,M.steel,false,false);
label('SUPPLY / '+String(Math.abs(x)),x,3.38,z-d/2-.22,3.2,.45,'#343a37')}
for(const args of W.buildings)building(...args);
function cargo(x,z,w,d,color){const m=fieldEnvironment.surface('painted container','metal',3,color,.35);box('container',x,1.5,z,w,3,d,m,true);for(let k=-d/2+.5;k<d/2;k+=.65)box('rib',x-w/2-.04,1.5,z+k,.08,2.8,.06,M.steel,false,false);label('09',x,1.8,z-d/2-.06,2,1,'#dbe6de')}
for(const args of W.cargos)cargo(...args);
for(const [x,z,w] of W.barriers){box('barrier',x,.65,z,w,1.3,1.2,M.concrete,true);box('warning stripe',x,.95,z-.62,w,.16,.03,M.yellow,false,false)}
for(const [x,z] of W.crates){box('crate',x,.6,z,1.4,1.2,1.4,M.wood,true);box('band',x,.65,z-.71,1.4,.12,.02,M.steel,false,false)}
function tree(x,z,scale=1){const trunk=cylinder('trunk',x,1.8*scale,z,.48*scale,3.6*scale,M.bark);trunk.isPickable=true;staticHits.add(trunk);obstacles.push({x,z,w:.3*scale,d:.3*scale});fieldEnvironment.tree(x,z,scale)}
for(const args of W.trees)tree(...args);
for(let i=0;i<14;i++){const a=i/14*Math.PI*2,r=140;const m=B.MeshBuilder.CreateSphere('distant ridge',{diameter:65,segments:16},scene);m.position.set(Math.sin(a)*r,-11,Math.cos(a)*r);m.scaling.set(1.4,.6+(i%3)*.15,1);m.material=M.grass;m.isPickable=false;m.receiveShadows=true}
fieldEnvironment.quality(highQuality);
// Blue field is a translucent volume with a bright ground boundary.
const zoneMat=new B.StandardMaterial('blue field',scene);zoneMat.diffuseColor=new C(.15,.5,1);zoneMat.emissiveColor=new C(.08,.32,.9);zoneMat.alpha=.13;zoneMat.backFaceCulling=false;zoneMat.disableLighting=true;zoneMat.depthFunction=B.Constants.LEQUAL;
const wall=B.MeshBuilder.CreateCylinder('zone wall',{diameter:2,height:22,tessellation:96,cap:B.Mesh.NO_CAP,sideOrientation:B.Mesh.DOUBLESIDE},scene);wall.position.y=11;wall.material=zoneMat;wall.isPickable=false;
function ring(name,color){const points=[];for(let i=0;i<=128;i++){const a=i/128*Math.PI*2;points.push(new V(Math.sin(a),.075,Math.cos(a)))}const m=B.MeshBuilder.CreateLines(name,{points},scene);m.color=color;m.isPickable=false;return m}
const zoneRing=ring('current circle',new C(.15,.55,1)),nextRing=ring('next circle',new C(1,1,.92));
function blocked(x,z,r=.4){if(Math.abs(x)>68-r||Math.abs(z)>68-r)return true;return obstacles.some(o=>Math.abs(x-o.x)<o.w+r&&Math.abs(z-o.z)<o.d+r)}
function advance(p,dx,dz,r=.4){if(!blocked(p.x+dx,p.z,r))p.x+=dx;if(!blocked(p.x,p.z+dz,r))p.z+=dz}
function visible(a,b){const delta=b.subtract(a),length=delta.length();if(length<.01)return true;const ray=new B.Ray(a,delta.scale(1/length),Math.max(0,length-.2));return !scene.pickWithRay(ray,m=>staticHits.has(m))?.hit}
// A* on a shared collision grid keeps bots out of walls and sends them through doors.
const cellSize=2,cols=68,origin=-68,nav=new Uint8Array(cols*cols);
for(let z=0;z<cols;z++)for(let x=0;x<cols;x++)nav[z*cols+x]=blocked(origin+(x+.5)*cellSize,origin+(z+.5)*cellSize,.45)?1:0;
function cell(p){return{x:Math.max(0,Math.min(cols-1,Math.floor((p.x-origin)/cellSize))),z:Math.max(0,Math.min(cols-1,Math.floor((p.z-origin)/cellSize)))}}
function route(from,to){const s=cell(from),g=cell(to),startIdx=s.z*cols+s.x;let end=g.z*cols+g.x;if(nav[end]){let best=Infinity;for(let dz=-3;dz<=3;dz++)for(let dx=-3;dx<=3;dx++){let x=g.x+dx,z=g.z+dz;if(x<0||x>=cols||z<0||z>=cols)continue;let i=z*cols+x;if(!nav[i]&&dx*dx+dz*dz<best){best=dx*dx+dz*dz;end=i}}}const cost=new Float32Array(cols*cols);cost.fill(Infinity);cost[startIdx]=0;const parent=new Int16Array(cols*cols);parent.fill(-1);const open=[startIdx],closed=new Uint8Array(cols*cols);let count=0;const gx=end%cols,gz=Math.floor(end/cols),heur=i=>Math.abs(i%cols-gx)+Math.abs(Math.floor(i/cols)-gz);while(open.length&&count++<4000){let best=0;for(let k=1;k<open.length;k++)if(cost[open[k]]+heur(open[k])<cost[open[best]]+heur(open[best]))best=k;const current=open.splice(best,1)[0];if(current===end){let path=[],n=end;while(n!==startIdx&&n>=0){path.unshift(new V(origin+(n%cols+.5)*cellSize,0,origin+(Math.floor(n/cols)+.5)*cellSize));n=parent[n]}return path}closed[current]=1;const x=current%cols,z=Math.floor(current/cols);for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,zz=z+dz;if(xx<0||xx>=cols||zz<0||zz>=cols)continue;const n=zz*cols+xx;if(nav[n]||closed[n])continue;const c=cost[current]+1;if(c<cost[n]){cost[n]=c;parent[n]=current;if(!open.includes(n))open.push(n)}}}return[]}
const lootVisuals=window.createLootVisuals(B,scene,M);
function lootItem(type,x,z,weapon=null,amount=60){const root=lootVisuals.create(type,weapon),color=type==='weapon'?(R.melee(weapon)?M.steel:weapon==='marksman'?M.purple:weapon==='smg'?M.armor:M.ammo):type==='helmet'?M.helmet:type==='vest'?M.armor:M[type]||M.ammo;root.position.set(x,0,z);const halo=B.MeshBuilder.CreateTorus('supply ground ring',{diameter:1.12,thickness:.023,tessellation:24},scene);halo.parent=root;halo.position.y=.04;halo.material=color;halo.isPickable=false;loot.push({type,x,z,weapon,amount,root,taken:false});return loot[loot.length-1]}
function populateLoot(spawn){for(const l of loot)l.root.dispose();loot.length=0;for(const item of W.loot()){const l=lootItem(item.type,item.x,item.z,item.weapon,item.amount);l.id=item.id}
if(!spawn)return;
// Solo gets the same guaranteed cache as an online round: a run away, in a direction that changes every time.
const[cx,cz]=W.cacheSpot(spawn[0],spawn[1]);let n=0;
for(const[type,ox,oz,weapon]of [['weapon',0,0,W.randomWeapon()],['ammo',.9,.5,null],['med',-.9,.5,null],['vest',0,-1.1,null],['helmet',-1.5,-.6,null]]){let lx=cx+ox,lz=cz+oz;if(W.blocked(lx,lz,.1)){lx=cx;lz=cz}lootItem(type,lx,lz,weapon,60).id='spawn-solo-'+(n++)}}
populateLoot();
const gun=new B.TransformNode('view weapon',scene);gun.parent=camera;gun.position.set(.23,-.23,.48);
function gunPart(name,x,y,z,w,h,d,m){const b=box(name,x,y,z,w,h,d,m,false,false);b.parent=gun;b.renderingGroupId=1;return b}
gunPart('receiver',0,0,.12,.12,.12,.39,M.dark);gunPart('rail',0,.076,.12,.085,.018,.38,M.steel);const barrel=gunPart('barrel',0,.01,.56,.035,.035,.35,M.dark);gunPart('grip',0,-.12,-.01,.075,.2,.09,M.dark);const mag=gunPart('magazine',0,-.11,.14,.09,.21,.12,M.steel);gunPart('stock',0,-.02,-.2,.09,.11,.24,M.dark);gunPart('handguard',0,0,.37,.1,.1,.21,M.steel);gunPart('sight left',-.025,.1,.04,.014,.05,.025,M.dark);gunPart('sight right',.025,.1,.04,.014,.05,.025,M.dark);gunPart('front sight',0,.082,.5,.013,.055,.02,M.dark);gunPart('right glove',.02,-.12,-.1,.12,.12,.13,M.pants);gunPart('left glove',-.03,-.08,.33,.12,.13,.13,M.pants);const scope=gunPart('scope',0,.11,.18,.09,.09,.28,M.dark);scope.setEnabled(false);
const hands=new B.TransformNode('view hands',scene);hands.parent=camera;hands.position.set(0,-.34,.58);
function handPart(parent,name,x,y,z,w,h,d,m){const b=box(name,x,y,z,w,h,d,m,false,false);b.parent=parent;b.renderingGroupId=1;return b}
// A closed fist built from forearm, wrist, palm, four knuckles and a thumb laid across the fingers.
function buildArm(side){
  const arm=new B.TransformNode(side>0?'right arm':'left arm',scene);arm.parent=hands;
  handPart(arm,'sleeve',0,-.015,-.2,.108,.105,.3,M.cloth);
  handPart(arm,'cuff',0,-.01,-.055,.1,.098,.035,M.pants);
  handPart(arm,'wrist',0,0,-.015,.083,.08,.07,M.skin);
  handPart(arm,'palm',0,.004,.045,.094,.1,.095,M.skin);
  handPart(arm,'curled fingers',0,-.012,.094,.09,.078,.05,M.skin);
  for(let i=0;i<4;i++)handPart(arm,'knuckle',(i-1.5)*.023,.042,.088,.021,.028,.05,M.skin);
  handPart(arm,'thumb',-side*.046,-.018,.052,.03,.034,.075,M.skin);
  handPart(arm,'thumb tip',-side*.036,-.016,.092,.028,.03,.03,M.skin);
  return arm;
}
const rightArm=buildArm(1),leftArm=buildArm(-1);
// A drawn blade rides in the right hand and sweeps through an arc instead of jabbing.
const bladeView=new B.TransformNode('view blade',scene);bladeView.parent=rightArm;bladeView.position.set(0,.02,.06);
const bladeSteel=handPart(bladeView,'view blade steel',0,0,.26,.055,.013,.42,M.blade);
const bladeEdge=handPart(bladeView,'view cutting edge',.022,0,.26,.02,.02,.4,M.blade);bladeEdge.rotation.z=.5;
handPart(bladeView,'view cross guard',0,0,.055,.105,.03,.03,M.dark);
handPart(bladeView,'view grip wrap',0,-.002,-.02,.05,.05,.13,M.grip);
bladeView.setEnabled(false);hands.setEnabled(false);
let punchTimer=0,punchSide=1,punchSpan=.34;
function swingHands(){const w=R.weapons[player.equipped];punchSpan=Math.max(.2,(w?.interval||.44)*.85);punchTimer=punchSpan;punchSide=R.innate(player.equipped)?-punchSide:1}
// One swing curve drives both the jab and the blade arc: 0 at rest, 1 fully extended.
function poseHands(moving){
  if(!hands.isEnabled())return;
  const blade=bladeView.isEnabled(),bob=moving?Math.sin(step)*.01:0;
  hands.position.y=-.34+bob-(healing?.16:0);hands.position.z=.58;
  // A real punch cocks back before it lands, so the curve dips negative first.
  const phase=punchTimer>0?1-punchTimer/punchSpan:0;
  const reach=punchTimer<=0?0:phase<.24?-Math.sin(phase/.24*Math.PI)*.28:Math.sin((phase-.24)/.76*Math.PI);
  for(const[side,arm]of [[1,rightArm],[-1,leftArm]]){
    const push=side===punchSide?reach:reach*.12;
    arm.setEnabled(side>0||!blade);
    arm.position.set(side*.205-side*push*.115,(side===punchSide?push*.045:0)-(blade&&side>0?.03:0),push*(blade?.2:.46));
    arm.rotation.set(-push*(blade?.15:.34),-side*.13+side*push*.11,blade&&side>0?-.5+reach*1.7:0);
  }
  if(blade){bladeSteel.scaling.z=bladeEdge.scaling.z=player.equipped==='machete'?1.5:1;bladeView.rotation.set(reach*.5,-.2+reach*.4,0)}
}
function roundGun(name,x,y,z,radius,length,m){const mesh=B.MeshBuilder.CreateCylinder(name,{diameter:radius*2,height:length,tessellation:16},scene);mesh.parent=gun;mesh.position.set(x,y,z);mesh.rotation.x=Math.PI/2;mesh.material=m;mesh.renderingGroupId=1;mesh.isPickable=false;return mesh}
barrel.setEnabled(false);roundGun('rifled barrel',0,.01,.57,.022,.36,M.dark);roundGun('muzzle brake',0,.01,.755,.029,.07,M.steel);
for(let i=0;i<9;i++)gunPart('rail tooth',0,.09,-.02+i*.04,.095,.012,.015,M.dark);
for(let i=0;i<5;i++){gunPart('handguard cooling slot',.052,.023,.29+i*.032,.005,.025,.018,M.dark);gunPart('magazine groove',.046,-.1,.1+i*.014,.006,.18,.006,M.dark)}
roundGun('optic housing',0,.12,.19,.045,.14,M.dark).setEnabled(false);
for(const x of [-.062,.062])for(const z of [-.025,.15,.23]){const bolt=B.MeshBuilder.CreateSphere('receiver screw',{diameter:.012,segments:8},scene);bolt.parent=gun;bolt.position.set(x,.012,z);bolt.material=M.steel;bolt.renderingGroupId=1;bolt.isPickable=false}
const guard=B.MeshBuilder.CreateTorus('trigger guard',{diameter:.11,thickness:.012,tessellation:20},scene);guard.parent=gun;guard.position.set(0,-.093,.035);guard.rotation.z=Math.PI/2;guard.scaling.z=.7;guard.material=M.dark;guard.renderingGroupId=1;guard.isPickable=false;
const muzzle=B.MeshBuilder.CreateSphere('flash',{diameter:.14,segments:5},scene);muzzle.parent=gun;muzzle.position.set(0,.01,.77);muzzle.material=M.flash;muzzle.renderingGroupId=1;muzzle.isPickable=false;muzzle.setEnabled(false);gun.setEnabled(false);
let player=R.newPlayer(),state='ready',time=0,clock=0,zone=R.zoneAt(0),yaw=0,pitch=0,reloading=0,healing=0,shotTimer=0,recoil=0,hitTimer=0,damageFade=0,noticeTimer=0,feedTimer=0,held=false,ads=false,nearest=null,step=0,hudTimer=0;
const keys=new Set(),move={x:0,y:0};let audio=null,soundOn=true,dragLook=null;const pointers={stick:null,look:null,fire:null};
function beep(freq,duration,volume=.07,type='sine'){if(!audio||!soundOn)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*.5),audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function shotSound(volume=.2){if(!audio||!soundOn)return;const n=audio.createBuffer(1,Math.floor(audio.sampleRate*.12),audio.sampleRate),d=n.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length)**3;const s=audio.createBufferSource(),g=audio.createGain(),f=audio.createBiquadFilter();s.buffer=n;g.gain.value=volume;f.type='lowpass';f.frequency.value=1800;s.connect(f);f.connect(g);g.connect(audio.destination);s.start();beep(90,.09,volume*.5,'triangle')}
function audioStart(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{})}catch{}}
function notify(text,seconds=2.5){$('notice').textContent=text;noticeTimer=seconds}
function feed(text){$('killfeed').textContent=text;feedTimer=5}
function inputMode(){document.body.classList.toggle('touch-mode',touch);$('inputmode').textContent=touch?'터치 조작':'마우스 조작'}inputMode();$('inputmode').onclick=()=>controls.toggleMode();$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='사운드 '+(soundOn?'ON':'OFF');if(soundOn)audioStart()};
function clearInput(){keys.clear();held=ads=false;move.x=move.y=0;dragLook=null;pointers.stick=pointers.look=pointers.fire=null;$('knob').style.transform='translate(0,0)'}
function lock(){if(touch||document.pointerLockElement===canvas)return;try{const p=canvas.requestPointerLock?.();p?.catch?.(()=>notify('마우스를 누른 채 드래그해 조준할 수도 있습니다',4))}catch{}}
function format(t){const seconds=Math.max(0,Math.ceil(t));return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}
function thirdView(){return thirdPerson&&!ads&&(state==='playing'||state==='finished')}
function updateGun(){const melee=R.melee(player.equipped),first=!thirdView();gun.setEnabled(first&&!!player.equipped&&!melee);hands.setEnabled(first&&melee);bladeView.setEnabled(melee&&!R.innate(player.equipped));scope.setEnabled(!melee&&player.equipped==='marksman');barrel.scaling.z=player.equipped==='marksman'?1.6:player.equipped==='smg'?.6:1;mag.scaling.y=player.equipped==='marksman'?.6:1;muzzle.position.z=player.equipped==='marksman'?.88:.77}
function ensureSelfBody(){if(selfBody||!soldierAssets)return;selfBody=makeSoldier('self',0,0);selfBody.bodyHit.isPickable=false;selfBody.headHit.isPickable=false;selfBody.root.setEnabled(false)}
function dropSelfBody(){if(!selfBody)return;disposeSoldier(selfBody);selfBody=null}
// Pull straight out along the view axis, then swing to the shoulder, stopping short of any wall behind.
function placeView(moving){
  if(!thirdView()){if(scene.activeCamera!==camera)scene.activeCamera=camera;selfBody?.root.setEnabled(false);return}
  ensureSelfBody();
  const matrix=B.Matrix.RotationYawPitchRoll(camera.rotation.y,camera.rotation.x,0);
  const delta=V.TransformCoordinates(new V(.78,.34,-4.1),matrix),span=delta.length();
  let reach=span;const pick=scene.pickWithRay(new B.Ray(camera.position,delta.scale(1/span),span),m=>staticHits.has(m));
  if(pick?.hit)reach=Math.max(.55,pick.distance-.3);
  viewCam.position.copyFrom(camera.position).addInPlace(delta.scale(reach/span));
  viewCam.rotation.copyFrom(camera.rotation);viewCam.fov=camera.fov;
  if(scene.activeCamera!==viewCam)scene.activeCamera=viewCam;
  if(selfBody){selfBody.root.setEnabled(player.hp>0);selfBody.root.position.set(camera.position.x,0,camera.position.z);selfBody.root.rotation.y=yaw;dressSoldier(selfBody,{helmet:player.helmet>0,vest:player.vest>0,equipped:player.equipped});modelAnimation(selfBody,moving?'Run':'Idle')}
}
function toggleView(){thirdPerson=!thirdPerson;updateGun();placeView(false);notify(thirdPerson?'3인칭 시점 · 조준하면 1인칭으로 전환됩니다':'1인칭 시점',2)}
function ui(){const w=R.weapons[player.equipped],slot=player.weapons[player.equipped],out=R.outsideZone(camera.position.x,camera.position.z,zone);$('health').textContent=Math.ceil(player.hp);$('healthbar').style.width=player.hp+'%';$('healthbar').style.background=player.hp<30?'#f56f53':'#f1efdc';$('armor').textContent='헬멧 '+Math.ceil(player.helmet)+' · 조끼 '+Math.ceil(player.vest);$('helmetbar').style.width=player.helmet+'%';$('armorbar').style.width=player.vest+'%';$('meds').textContent='구급팩 '+player.kits+' · '+(touch?'치료 버튼':controls.keyLabel('heal')+' 사용');$('kits').textContent=player.kits;$('ammo').textContent=slot?slot.ammo:'—';$('reserve').textContent=player.reserve;$('weapon').textContent=w?w.name+' / '+w.label:'맨손 · 무기를 찾으세요';$('reloadstatus').textContent=reloading>0?'재장전 중':healing>0?'치료 중':w?'공용 탄약':(touch?'획득 버튼으로 무기 확보':controls.keyLabel('collect')+'로 무기 획득');$('kills').textContent=player.kills;$('alive').textContent=netMode&&netState?netState.players.filter(p=>p.hp>0).length:enemies.length+(player.hp>0?1:0);$('phase').textContent='PHASE 0'+zone.phase;$('zonetimer').textContent=(zone.closing?'자기장 축소 중 ':'안전구역 축소까지 ')+format(zone.seconds);$('zonehint').textContent=out?'구역 밖! 초당 '+zone.dps+' 피해':'안전구역 반경 '+Math.round(zone.radius)+'m → '+zone.target+'m';$('zonehint').style.color=out?'#ffbb94':'#d1e1e6';$('zoneprogress').style.width=Math.max(0,zone.seconds/(zone.closing?R.stages[zone.phase-1].shrink:R.stages[zone.phase-1].wait)*100)+'%';$('slots').innerHTML=Object.keys(R.weapons).map((id,i)=>`<span class="${id===player.equipped?'active':''}" style="opacity:${R.held(player,id)?1:.5}">${i+1} ${R.held(player,id)?R.weapons[id].name:'—'}</span>`).join('');$('actionprogress').hidden=!(reloading||healing);$('actionprogress').textContent=healing?'치료 '+healing.toFixed(1)+'초':reloading?'재장전 '+reloading.toFixed(1)+'초':'';$('aim').style.borderColor=ads?'#efbf56':'';drawMap()}
const map=$('minimap').getContext('2d');function drawMap(){const size=320,s=size/148,c=size/2;map.clearRect(0,0,size,size);map.fillStyle='#455b46';map.fillRect(0,0,size,size);map.fillStyle='#84928a';map.fillRect(c-5*s,0,10*s,size);map.fillRect(0,c-14*s,size,9*s);map.fillStyle='#b3b7a6';for(const o of obstacles)map.fillRect(c+(o.x-o.w)*s,c-(o.z+o.d)*s,o.w*2*s,o.d*2*s);map.fillStyle='#196ccf50';map.beginPath();map.rect(0,0,size,size);map.arc(c,c,Math.max(0,zone.radius*s),0,Math.PI*2,true);map.fill('evenodd');map.strokeStyle='#68b7ff';map.lineWidth=3;map.beginPath();map.arc(c,c,Math.max(0,zone.radius*s),0,Math.PI*2);map.stroke();map.strokeStyle='#fff';map.lineWidth=2;map.setLineDash([7,5]);map.beginPath();map.arc(c,c,Math.max(0,zone.target*s),0,Math.PI*2);map.stroke();map.setLineDash([]);for(const l of loot)if(!l.taken){map.fillStyle=l.type==='weapon'?'#f5c65c':'#d5eadc';map.fillRect(c+l.x*s-1.5,c-l.z*s-1.5,3,3)}map.save();map.translate(c+camera.position.x*s,c-camera.position.z*s);map.rotate(yaw);map.fillStyle='#fff';map.strokeStyle='#182b31';map.lineWidth=2;map.beginPath();map.moveTo(0,-9);map.lineTo(-6,6);map.lineTo(0,3);map.lineTo(6,6);map.closePath();map.fill();map.stroke();map.restore()}
let soldierAssets=null,lobbySoldier=null,charactersReady=false;
const corpses=[];
function modelAnimation(e,name){if(e.motion===name)return;e.motion=name;for(const [key,a] of Object.entries(e.animations)){if(key===name){a.play(true);a.speedRatio=name==='Run'?1:name==='Walk'?1.25:1}else a.stop()}}
function updateWorld(node){for(const child of node.getDescendants(false))child.computeWorldMatrix(true);node.computeWorldMatrix(true)}
// Rotate joints in parent space, so the imported glTF coordinate conversion stays intact.
function pointJoint(joint,child,target){const parent=joint.parent,inv=parent.getWorldMatrix().clone().invert();const origin=V.TransformCoordinates(joint.getAbsolutePosition(),inv),current=V.TransformCoordinates(child.getAbsolutePosition(),inv).subtract(origin).normalize(),desired=V.TransformCoordinates(target,inv).subtract(origin).normalize();const dot=Math.max(-1,Math.min(1,V.Dot(current,desired)));if(dot>.99999)return;let axis=V.Cross(current,desired);if(axis.lengthSquared()<1e-8)axis=V.Cross(current,new V(1,0,0));if(axis.lengthSquared()<1e-8)axis=V.Cross(current,new V(0,0,1));const delta=B.Quaternion.RotationAxis(axis.normalize(),Math.acos(dot));joint.rotationQuaternion=delta.multiply(joint.rotationQuaternion||B.Quaternion.FromEulerVector(joint.rotation));joint.computeWorldMatrix(true);child.computeWorldMatrix(true)}
function solveArm(upper,lower,hand,target,pole){if(!upper||!lower||!hand)return;upper.computeWorldMatrix(true);lower.computeWorldMatrix(true);hand.computeWorldMatrix(true);const a=upper.getAbsolutePosition().clone(),b=lower.getAbsolutePosition().clone(),c=hand.getAbsolutePosition().clone(),l1=V.Distance(a,b),l2=V.Distance(b,c),delta=target.subtract(a),distance=Math.min(delta.length(),(l1+l2)*.97);if(distance<.001)return;const dir=delta.normalize(),perp=pole.subtract(a);perp.subtractInPlace(dir.scale(V.Dot(perp,dir))).normalize();const along=(l1*l1-l2*l2+distance*distance)/(2*distance),height=Math.sqrt(Math.max(0,l1*l1-along*along));const elbow=a.add(dir.scale(along)).add(perp.scale(height));pointJoint(upper,lower,elbow);hand.computeWorldMatrix(true);pointJoint(lower,hand,a.add(dir.scale(distance)))}
function poseSoldier(e){if(!e.rig||!e.root.isEnabled())return;updateWorld(e.model);const world=e.root.getWorldMatrix(),local=p=>V.TransformCoordinates(p,world),bob=e.motion==='Idle'?0:Math.sin(e.phase)*.012;
solveArm(e.rig.RightArm,e.rig.RightForeArm,e.rig.RightHand,local(new V(.14,1.27+bob,.31)),local(new V(.65,1.1,.02)));
solveArm(e.rig.LeftArm,e.rig.LeftForeArm,e.rig.LeftHand,local(new V(-.07,1.29+bob,.57)),local(new V(-.6,1.08,.05)));
e.rifle.position.y=1.29+bob;e.rifle.position.z=.42-(e.flashTime>0?.025:0);
if(e.rig.Head){e.rig.Head.computeWorldMatrix(true);const center=e.rig.Head.getAbsolutePosition(),inv=world.clone().invert();e.headHit.position.copyFrom(V.TransformCoordinates(center,inv));e.headHit.position.y+=.08}
if(e.gearVest)e.gearVest.position.y=1.16+bob;
if(e.blade)e.blade.position.y=1.22+bob;
if(e.gearHelmet?.isEnabled()){e.gearHelmet.position.copyFrom(e.headHit.position);e.gearHelmet.position.y+=.07}
}
function dressSoldier(e,{helmet,vest,equipped}){
  e.gearHelmet?.setEnabled(!!helmet);e.gearVest?.setEnabled(!!vest);
  const melee=R.melee(equipped);
  e.rifle.setEnabled(!!equipped&&!melee);
  e.blade?.setEnabled(melee&&!R.innate(equipped));
}
function disposeSoldier(e){for(const a of e.animationGroups)a.dispose();for(const sk of e.skeletons)sk.dispose();e.root.dispose()}
function makeSoldier(id,x,z){const root=new B.TransformNode('soldier '+id,scene);root.position.set(x,0,z);const e={id,root,hp:100,helmet:0,vest:0,equipped:'carbine',speed:2.4+Math.random()*.5,attack:2+Math.random()*2,phase:Math.random()*6,target:null,path:[],plan:Math.random(),rethink:Math.random(),fireCount:0,flashTime:0,motion:null};
const instance=soldierAssets.instantiateModelsToScene(name=>'bot'+id+'_'+name,false,{doNotInstantiate:true});e.animationGroups=instance.animationGroups;e.skeletons=instance.skeletons;e.model=new B.TransformNode('body rig',scene);e.model.parent=root;e.model.rotation.y=Math.PI;
for(const node of instance.rootNodes){node.parent=e.model;node.setEnabled(true)}
// Normalize height once; preserve the skinning rig and shared geometry/materials.
let low=Infinity,high=-Infinity;for(const mesh of e.model.getChildMeshes()){mesh.computeWorldMatrix(true);if(mesh.getTotalVertices()){const b=mesh.getBoundingInfo().boundingBox;low=Math.min(low,b.minimumWorld.y);high=Math.max(high,b.maximumWorld.y)}}
const scale=1.82/(high-low);e.model.scaling.setAll(scale);e.model.position.y=-low*scale;
e.rig={};for(const node of e.model.getDescendants()){const name=node.name.split(':').pop();if(['Head','RightArm','RightForeArm','RightHand','LeftArm','LeftForeArm','LeftHand'].includes(name))e.rig[name]=node}
for(const mesh of e.model.getChildMeshes()){mesh.isPickable=false;mesh.receiveShadows=true;mesh.alwaysSelectAsActiveMesh=true;if(mesh.getTotalVertices())shadow.addShadowCaster(mesh)}
e.animations={};for(const a of e.animationGroups){const name=['Idle','Walk','Run'].find(n=>a.name.endsWith(n));if(name)e.animations[name]=a;for(const t of a.targetedAnimations){t.animation.enableBlending=true;t.animation.blendingSpeed=.12}}
function hitbox(name,y,height,radius,head=false){const m=B.MeshBuilder.CreateCapsule(name,{height,radius,tessellation:8,subdivisions:1},scene);m.parent=root;m.position.y=y;m.visibility=0;m.isPickable=true;m.metadata={enemy:e,head};return m}
e.bodyHit=hitbox('body hitbox',.85,1.35,.25);e.headHit=hitbox('head hitbox',1.67,.31,.15,true);
e.rifle=new B.TransformNode('rifle',scene);e.rifle.parent=root;e.rifle.position.set(.12,1.29,.42);
for(const [name,px,py,pz,w,h,d,material] of [['receiver',0,0,0,.085,.09,.32,M.dark],['stock',0,0,-.24,.07,.11,.2,M.pants],['barrel',0,.015,.35,.028,.028,.37,M.dark],['handguard',0,.005,.18,.075,.085,.2,M.steel],['magazine',0,-.09,.01,.055,.16,.08,M.dark],['rail',0,.057,.07,.055,.018,.29,M.steel],['grip',0,-.075,-.09,.055,.14,.05,M.dark]]){const m=box(name,px,py,pz,w,h,d,material,false,false);m.parent=e.rifle}
// Picked-up gear is worn on the body, so what a player carries is what everyone sees.
const shell=B.MeshBuilder.CreateSphere('worn helmet shell',{diameter:.3,segments:12,slice:.56},scene);
e.gearHelmet=new B.TransformNode('worn helmet',scene);e.gearHelmet.parent=root;
shell.parent=e.gearHelmet;shell.scaling.set(1.06,1,1.18);shell.material=M.helmetShell;shell.isPickable=false;shell.receiveShadows=true;shadow.addShadowCaster(shell);
const rim=B.MeshBuilder.CreateTorus('worn helmet rim',{diameter:.3,thickness:.026,tessellation:16},scene);
rim.parent=e.gearHelmet;rim.position.y=-.012;rim.scaling.z=1.18;rim.material=M.helmetShell;rim.isPickable=false;
const nape=box('nape guard',0,-.03,.15,.2,.09,.05,M.helmetShell,false,false);nape.parent=e.gearHelmet;
e.gearHelmet.setEnabled(false);
e.gearVest=new B.TransformNode('worn vest',scene);e.gearVest.parent=root;
for(const[name,x,y,z,w,h,d]of [['chest plate',0,0,-.1,.4,.46,.1],['back plate',0,0,.11,.38,.44,.09],['left strap',-.15,.25,0,.08,.09,.23],['right strap',.15,.25,0,.08,.09,.23],['belt pouches',0,-.2,-.15,.32,.13,.09]]){
  const piece=box(name,x,y,z,w,h,d,M.kevlar,false,false);piece.parent=e.gearVest;piece.receiveShadows=true;shadow.addShadowCaster(piece);
}
e.gearVest.setEnabled(false);
// A drawn blade replaces the rifle in the hands.
e.blade=new B.TransformNode('held blade',scene);e.blade.parent=root;e.blade.position.set(.17,1.22,.4);e.blade.rotation.set(-.25,0,0);
const heldBlade=box('held blade steel',0,0,.22,.06,.014,.42,M.blade,false,false);heldBlade.parent=e.blade;
const heldGuard=box('held cross guard',0,0,.02,.11,.03,.035,M.dark,false,false);heldGuard.parent=e.blade;
const heldGrip=B.MeshBuilder.CreateCylinder('held grip',{height:.17,diameter:.05,tessellation:8},scene);
heldGrip.parent=e.blade;heldGrip.rotation.x=Math.PI/2;heldGrip.position.z=-.09;heldGrip.material=M.grip;heldGrip.isPickable=false;
e.blade.setEnabled(false);
const flash=B.MeshBuilder.CreateSphere('enemy muzzle flash',{diameter:.15,segments:5},scene);flash.parent=e.rifle;flash.position.set(0,.015,.57);flash.material=M.flash;flash.isPickable=false;flash.setEnabled(false);e.flash=flash;modelAnimation(e,'Idle');return e}
function spawnBot(i){const spots=[[-39,-40],[38,-40],[-37,-7],[39,-1],[-38,30],[40,37],[-10,50],[14,53],[-50,48],[53,51],[-53,-48],[52,-49]],p=spots[i];
  const e=makeSoldier(i+1,p[0],p[1]);
  e.helmet=Math.random()<.45?100:0;e.vest=Math.random()<.6?70:0;e.equipped=Math.random()<.18?'machete':'carbine';
  dressSoldier(e,e);enemies.push(e)}
scene.onAfterAnimationsObservable.add(()=>{if(selfBody&&selfBody.root.isEnabled())poseSoldier(selfBody);for(const e of enemies)poseSoldier(e);for(const e of netPeers.values())if(e.hp>0)poseSoldier(e);if((state==='ready'||state==='lobby')&&lobbySoldier)poseSoldier(lobbySoldier)});
async function loadCharacters(){try{start.disabled=true;start.textContent='캐릭터 불러오는 중…';boot?.stage('캐릭터와 텍스처 다운로드 중…');soldierAssets=await B.SceneLoader.LoadAssetContainerAsync('assets/','soldier.glb',scene);for(const material of soldierAssets.materials){if(material instanceof B.PBRMaterial){material.metallic=0;material.roughness=.85;material.environmentIntensity=.6;material.directIntensity=1;material.albedoColor=new C(.85,.85,.85)}}for(const a of soldierAssets.animationGroups)a.stop();lobbySoldier=makeSoldier(0,2.1,-51);lobbySoldier.root.rotation.y=Math.PI+.12;camera.position.set(-1,1.6,-56);camera.rotation.set(.04,.02,0);charactersReady=true;boot?.stage('3D 화면 준비 중…');scene.executeWhenReady(()=>{start.disabled=false;start.textContent='혼자 플레이 →';boot?.ready();window.GameOnline?.ready()})}catch(error){console.error(error);startupFailure('인체 모델을 불러오지 못했습니다. 연결을 확인하고 새로고침해 주세요.',error);start.disabled=true;start.textContent='캐릭터 로딩 실패'}}
loadCharacters();

function resetRound(){if(!charactersReady)return;if(lobbySoldier){lobbySoldier.root.setEnabled(false);for(const a of lobbySoldier.animationGroups)a.stop()}for(const c of corpses)disposeSoldier(c.e);corpses.length=0;for(const e of enemies)disposeSoldier(e);enemies.length=0;for(const e of effects)e.mesh.dispose();effects.length=0;dropSelfBody();populateLoot([0,-52]);for(let i=0;i<12;i++)spawnBot(i);player=R.newPlayer();time=clock=0;zone=R.zoneAt(0);yaw=pitch=0;reloading=healing=shotTimer=recoil=hitTimer=damageFade=0;camera.position.set(0,1.7,-52);camera.rotation.set(0,0,0);nearest=null;clearInput();updateGun();state='playing';$('screen').hidden=true;$('hud').hidden=false;$('touch').hidden=!touch;$('killfeed').textContent='';$('damage').style.opacity=0;$('zonewash').style.opacity=0;audioStart();notify('보급품은 매 라운드 무작위로 흩어집니다 · 맨손으로도 싸울 수 있어요 · '+(touch?'시점 버튼':controls.keyLabel('view'))+' 시점 전환',6);ui();lock()}
function pause(){if(netMode){netMenu();return}if(state!=='playing')return;state='paused';for(const e of enemies)for(const a of e.animationGroups)a.pause();clearInput();if(document.pointerLockElement)document.exitPointerLock();$('screen').hidden=false;$('touch').hidden=true;$('screen-title').textContent='전장 일시정지';$('screen-desc').textContent='이어하기를 누르면 자기장과 전투가 다시 진행됩니다.';start.textContent='전투 이어하기 →'}
function resume(){if(netMode){netResume();return}state='playing';for(const e of enemies)e.animations[e.motion]?.play(true);clearInput();$('screen').hidden=true;$('touch').hidden=!touch;audioStart();lock()}
function end(won,cause=''){if(state!=='playing')return;state=won?'won':'lost';for(const e of enemies)for(const a of e.animationGroups)a.pause();clearInput();if(document.pointerLockElement)document.exitPointerLock();$('screen').hidden=false;$('touch').hidden=true;$('screen-title').textContent=won?'#1 최후의 생존자':'#'+(enemies.length+1)+' 전투 종료';$('screen-desc').textContent=`${player.kills}명 처치 · ${Math.floor(time)}초 생존. ${won?'전장의 마지막 생존자가 되었습니다.':cause+' 다음에는 엄폐물과 안전구역을 활용하세요.'}`;start.textContent='새 전장에 투입 →';ui();beep(won?650:110,.5,.1)}
start.onclick=()=>netMode?(state==='paused'?netResume():window.GameOnline.open()):(state==='paused'?resume():resetRound());$('pause').onclick=pause;
function die(e,killer){const index=enemies.indexOf(e);if(index<0)return;const p=e.root.position.clone();for(const a of e.animationGroups)a.pause();e.bodyHit.isPickable=false;e.headHit.isPickable=false;e.flash.setEnabled(false);corpses.push({e,age:0});enemies.splice(index,1);lootItem('ammo',p.x,p.z,null,30);if(Math.random()<.35)lootItem('med',p.x+.8,p.z);if(killer==='player'){player.kills++;feed('YOU → BOT '+String(e.id).padStart(2,'0'));beep(470,.07,.07)}else feed((killer==='zone'?'자기장':killer)+' → BOT '+String(e.id).padStart(2,'0'));if(enemies.length===0&&player.hp>0)end(true);ui()}
function hurt(amount,cause,zoneDamage=false,head=false){if(state!=='playing')return;R.damage(player,amount,zoneDamage,head);if(!zoneDamage){damageFade=.75;healing=0;beep(65,.08,.09,'sawtooth')}if(player.hp<=0)end(false,cause);ui()}
function trace(a,b,color){const m=B.MeshBuilder.CreateLines('tracer',{points:[a,b]},scene);m.color=color;m.isPickable=false;effects.push({mesh:m,life:.12})}
function impact(p){const m=B.MeshBuilder.CreateSphere('impact',{diameter:.09,segments:4},scene);m.position.copyFrom(p);m.material=M.yellow;m.isPickable=false;effects.push({mesh:m,life:.16})}
function searchLoot(){nearest=null;let distance=3.1;for(const l of loot){if(l.taken)continue;const d=Math.hypot(camera.position.x-l.x,camera.position.z-l.z);if(d<distance&&visible(camera.position,new V(l.x,.45,l.z))){distance=d;nearest=l}}$('pickup').hidden=!nearest||(netMode&&(netState?.phase!=='playing'||player.hp<=0));$('loot').classList.toggle('available',!!nearest);if(nearest)$('loot-icon').className='loot-icon '+nearest.type;$('loot').style.opacity=nearest?'1':'.5';if(nearest){$('lootname').textContent=nearest.type==='weapon'?R.weapons[nearest.weapon].name:nearest.type==='ammo'?'탄약 +'+nearest.amount:nearest.type==='med'?'구급팩 +1':nearest.type==='helmet'?'전술 헬멧':'방탄 조끼';$('loottype').textContent=nearest.type==='weapon'?R.weapons[nearest.weapon].label:nearest.type==='med'?(touch?'치료 버튼':controls.keyLabel('heal'))+' · 3초 치료 · 체력 +65':nearest.type==='helmet'?'머리 피해 흡수 · 내구도 100':nearest.type==='vest'?'몸통 피해 흡수 · 내구도 100':'모든 총기에 사용';$('pickup').querySelector('b').textContent=touch?'터치해 획득':controls.keyLabel('collect')+' 획득'}}
function collect(){if(netMode){netAction('collect');return}if(state!=='playing')return;searchLoot();if(!nearest){notify('가까운 보급품이 없습니다',1);return}const old=player.equipped;if(R.collect(player,nearest)){nearest.root.setEnabled(false);notify(nearest.type==='weapon'?R.weapons[nearest.weapon].name+' 확보':'보급품 획득',1.4);if(old!==player.equipped){reloading=healing=0;updateGun()}beep(710,.08,.06);searchLoot();ui()}else notify(nearest.type==='med'?'구급팩을 더 들 수 없습니다':'이미 방탄복이 가득 찼습니다',1.5)}
function equip(id){if(netMode){netAction('equip',id);return}if(state!=='playing'||!R.held(player,id)||id===player.equipped)return;player.equipped=id;reloading=healing=0;held=false;updateGun();ui()}
function swap(){const owned=Object.keys(R.weapons).filter(id=>R.held(player,id));if(owned.length) equip(owned[(owned.indexOf(player.equipped)+1)%owned.length])}
function reload(){if(netMode){netAction('reload');return}const w=R.weapons[player.equipped],s=player.weapons[player.equipped];if(state!=='playing'||!w||reloading||s.ammo===w.mag)return;if(player.reserve<=0){notify('탄약이 없습니다. 보급품을 찾으세요',1.5);return}reloading=w.reload;healing=0;held=false;beep(280,.1,.04,'square');ui()}
function heal(){if(netMode){netAction('heal');return}if(state!=='playing'||healing)return;if(!player.kits){notify('구급팩이 없습니다',1.5);return}if(player.hp>=100){notify('체력이 가득 찼습니다',1.5);return}healing=3;reloading=0;held=false;notify('치료 중 · 사격하거나 맞으면 취소됩니다',2);ui()}
function shoot(){if(netMode){netShot();return}if(state!=='playing'||shotTimer>0||reloading)return;const w=R.weapons[player.equipped],s=player.weapons[player.equipped];if(!w){shotTimer=.5;return}const melee=w.melee===true;if(!melee){if(!s){shotTimer=.5;notify((touch?'획득 버튼':controls.keyLabel('collect'))+'으로 무기를 먼저 획득하세요',1.5);return}if(s.ammo<=0){reload();shotTimer=.2;return}s.ammo--;muzzle.setEnabled(true);shotSound()}else{swingHands();beep(R.innate(player.equipped)?180:300,.09,.05,'square')}healing=0;shotTimer=w.interval;recoil=melee?0:player.equipped==='marksman'?.075:.045;const ray=camera.getForwardRay(w.range);const pick=scene.pickWithRay(ray,m=>m.isPickable===true);const endPoint=pick?.hit?pick.pickedPoint:ray.origin.add(ray.direction.scale(w.range));if(!melee)trace(camera.position.add(new V(.1,-.1,0)),endPoint,new C(1,.85,.4));if(pick?.hit){const e=pick.pickedMesh.metadata?.enemy;if(e&&e.hp>0){const head=pick.pickedMesh.metadata.head;R.damage(e,w.damage*(head?(melee?1.5:2.5):1));hitTimer=.13;$('hitmarker').style.color=head?'#ffad52':'#fff';if(e.hp<=0)die(e,'player')}if(!melee)impact(pick.pickedPoint)}ui()}
$('loot').onclick=collect;$('pickup').onclick=collect;$('reload').onclick=reload;$('heal').onclick=heal;$('swap').onclick=swap;$('view').onclick=toggleView;$('aim').onclick=()=>{if(state==='playing')ads=!ads};
function planBot(e,target){e.path=route(e.root.position,target);e.plan=1.5+Math.random()*.4}
function updateBots(dt){for(const e of [...enemies]){if(state!=='playing')break;const p=e.root.position,oldX=p.x,oldZ=p.z;e.attack-=dt;e.plan-=dt;e.rethink-=dt;e.flashTime-=dt;e.flash.setEnabled(e.flashTime>0);if(R.outsideZone(p.x,p.z,zone)){R.damage(e,zone.dps*dt,true);if(e.hp<=0){die(e,'zone');continue}}
const unsafe=Math.hypot(p.x,p.z)>Math.max(1,zone.target-3),eye=new V(p.x,1.45,p.z);
if(e.rethink<=0){e.rethink=.35+Math.random()*.25;let best=45;e.target=null;const candidates=[{id:'player',position:camera.position,actor:player},...enemies.filter(a=>a!==e).map(a=>({id:a.id,position:new V(a.root.position.x,1.45,a.root.position.z),actor:a}))];for(const t of candidates){const d=V.Distance(eye,t.position);if(d<best&&t.actor.hp>0&&visible(eye,t.position)){best=d;e.target=t}}}
let target=e.target;if(target&&target.actor.hp<=0)target=e.target=null;let dest=new V(0,0,0),moving=true;const centerRadius=Math.min(zone.target*.65,25),angle=e.id*2.399;dest.set(Math.sin(angle)*centerRadius,0,Math.cos(angle)*centerRadius);
if(target){const tp=target.id==='player'?camera.position:new V(target.actor.root.position.x,1.45,target.actor.root.position.z),d=V.Distance(eye,tp);e.root.rotation.y=Math.atan2(tp.x-p.x,tp.z-p.z);if(!unsafe&&d>14)dest=new V(tp.x,0,tp.z);else if(!unsafe){dest=new V(p.x+Math.cos(clock+e.id)*3,0,p.z+Math.sin(clock+e.id)*3);moving=false;if(e.plan<=0)planBot(e,dest)}if(d<48&&e.attack<=0&&time>8&&visible(eye,tp)){e.attack=.75+Math.random()*.6;e.flashTime=.08;e.fireCount++;const hit=Math.random()<(target.id==='player'?.24:.4)*(d<18?1.4:1);const aim=tp.add(new V(hit?0:(Math.random()-.5)*2.4,hit?0:Math.random()*.9,0));trace(eye,aim,new C(1,.59,.23));if(V.Distance(eye,camera.position)<35)shotSound(.045);if(hit){if(target.id==='player')hurt(9,'적의 사격에 쓰러졌습니다.');else{R.damage(target.actor,13);if(target.actor.hp<=0)die(target.actor,'BOT '+e.id)}}}}
else if(e.path.length)e.root.rotation.y=Math.atan2(e.path[0].x-p.x,e.path[0].z-p.z);
if(e.plan<=0)planBot(e,dest);if(e.path.length){const next=e.path[0],dx=next.x-p.x,dz=next.z-p.z,d=Math.hypot(dx,dz);if(d<.65)e.path.shift();else{const speed=(unsafe?3.5:e.speed)*(moving?1:.55);advance(p,dx/d*speed*dt,dz/d*speed*dt,.36);e.phase+=dt*speed*4}}const actualSpeed=Math.hypot(p.x-oldX,p.z-oldZ)/Math.max(dt,.001);modelAnimation(e,actualSpeed>2.2?'Run':actualSpeed>.15?'Walk':'Idle')}}
function tick(dt){clock+=dt;if(netMode){netTick(dt);return}if(state==='ready'){camera.rotation.y=.02+Math.sin(clock*.08)*.015;return}if(state!=='playing')return;time+=dt;const previous=zone;zone=R.zoneAt(time);if(zone.phase!==previous.phase)notify('자기장 '+zone.phase+'단계 · 다음 원으로 이동하세요',3);else if(zone.closing&&!previous.closing){notify('자기장이 좁아집니다!',3);beep(230,.6,.08)}wall.scaling.set(Math.max(.001,zone.radius),1,Math.max(.001,zone.radius));zoneRing.scaling.set(zone.radius,1,zone.radius);nextRing.scaling.set(zone.target,1,zone.target);$('zonewash').style.opacity=R.outsideZone(camera.position.x,camera.position.z,zone)?'.9':'0';if(R.outsideZone(camera.position.x,camera.position.z,zone))hurt(zone.dps*dt,'자기장 밖에서 쓰러졌습니다.',true);if(state!=='playing')return;
shotTimer=Math.max(0,shotTimer-dt);punchTimer=Math.max(0,punchTimer-dt);recoil=Math.max(0,recoil-dt*.55);damageFade=Math.max(0,damageFade-dt*1.8);hitTimer=Math.max(0,hitTimer-dt);noticeTimer-=dt;feedTimer-=dt;if(noticeTimer<=0)$('notice').textContent='';if(feedTimer<=0)$('killfeed').textContent='';$('damage').style.opacity=damageFade;$('hitmarker').style.opacity=hitTimer>0?1:0;muzzle.setEnabled(recoil>.025);
if(reloading>0){reloading-=dt;if(reloading<=0){reloading=0;R.reload(player);beep(420,.06,.04,'square');ui()}}
if(healing>0){healing-=dt;if(healing<=0){healing=0;R.heal(player);beep(650,.15,.06);ui()}}
let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+move.x,mz=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-move.y,length=Math.hypot(mx,mz);if(length>1){mx/=length;mz/=length}const speed=healing?1.8:ads?2.7:keys.has('ShiftLeft')?7:4.8;advance(camera.position,(mx*Math.cos(yaw)+mz*Math.sin(yaw))*speed*dt,(-mx*Math.sin(yaw)+mz*Math.cos(yaw))*speed*dt);if(length>.1)step+=dt*10;camera.position.y=1.7+(length>.1?Math.sin(step)*.02:0);camera.rotation.set(pitch-recoil*.2,yaw,0);camera.fov+=((ads&&!R.melee(player.equipped)?(player.equipped==='marksman'?.45:.7):1.08)-camera.fov)*Math.min(1,dt*12);gun.position.x+=( (ads?0:.23)-gun.position.x)*Math.min(1,dt*12);gun.position.y=-.23+(length>.1?Math.sin(step)*.009:0)-(reloading||healing?.16:0);gun.position.z=.48-recoil;gun.rotation.x=reloading?-.45:0;poseHands(length>.1);placeView(length>.1);
if(held)shoot();if(state!=='playing')return;updateBots(dt);for(let i=corpses.length-1;i>=0;i--){const c=corpses[i];c.age+=dt;c.e.root.rotation.x=-Math.min(1,c.age/.45)*Math.PI/2;if(c.age>5){disposeSoldier(c.e);corpses.splice(i,1)}}for(let i=effects.length-1;i>=0;i--){effects[i].life-=dt;if(effects[i].life<=0){effects[i].mesh.dispose();effects.splice(i,1)}}hudTimer-=dt;if(hudTimer<=0){searchLoot();ui();hudTimer=.12}}
addEventListener('keydown',e=>{if(controls.modalOpen||controls.editing||window.GameOnline?.modalOpen)return;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.repeat)return;keys.add(e.code);if(e.code===controls.code('collect'))collect();if(e.code===controls.code('reload'))reload();if(e.code===controls.code('heal'))heal();if(e.code===controls.code('swap'))swap();if(e.code===controls.code('view'))toggleView();if(e.code==='Escape')pause();if(/^Digit[1-6]$/.test(e.code))equip(Object.keys(R.weapons)[Number(e.code.slice(-1))-1])});addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||touch)return;if(e.button===2){ads=true;return}if(e.button!==0)return;held=true;if(netMode)netShot();dragLook={x:e.clientX,y:e.clientY};lock()});addEventListener('pointerup',e=>{if(touch)return;if(e.button===2)ads=false;if(e.button===0){held=false;dragLook=null}});canvas.addEventListener('pointercancel',clearInput);canvas.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(state!=='playing'||touch)return;const sensitivity=ads?.0013:.0024;if(document.pointerLockElement===canvas){yaw+=e.movementX*sensitivity;pitch+=e.movementY*sensitivity}else if(dragLook){yaw+=(e.clientX-dragLook.x)*.004;pitch+=(e.clientY-dragLook.y)*.004;dragLook={x:e.clientX,y:e.clientY}}pitch=Math.max(-1.25,Math.min(1.25,pitch))});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing'&&!touch)pause()});addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function pad(node,type,down,onMove,up){node.addEventListener('pointerdown',e=>{if(state!=='playing'||pointers[type]!==null)return;e.preventDefault();pointers[type]=e.pointerId;controls.capturePointer(node,e.pointerId);down(e)});addEventListener('pointermove',e=>{if(pointers[type]===e.pointerId)onMove(e)});for(const n of ['pointerup','pointercancel','lostpointercapture'])addEventListener(n,e=>{if(pointers[type]===e.pointerId){pointers[type]=null;up()}})}
let stickOrigin={x:0,y:0},lookOrigin={x:0,y:0};function stickMove(e){let x=e.clientX-stickOrigin.x,y=e.clientY-stickOrigin.y,d=Math.hypot(x,y),s=d>36?36/d:1;x*=s;y*=s;move.x=x/36;move.y=y/36;$('knob').style.transform=`translate(${x}px,${y}px)`}
pad($('stick'),'stick',e=>{const r=$('stick').getBoundingClientRect();stickOrigin={x:r.left+r.width/2,y:r.top+r.height/2};stickMove(e)},stickMove,()=>{move.x=move.y=0;$('knob').style.transform='translate(0,0)'});pad($('look'),'look',e=>{lookOrigin={x:e.clientX,y:e.clientY}},e=>{const s=ads?.0025:.005;yaw+=(e.clientX-lookOrigin.x)*s;pitch=Math.max(-1.25,Math.min(1.25,pitch+(e.clientY-lookOrigin.y)*s));lookOrigin={x:e.clientX,y:e.clientY}},()=>{});pad($('fire'),'fire',()=>{held=true;shoot()},()=>{},()=>{held=false});
// Multiplayer adapter: rendering and prediction only. Combat/inventory stay on the server.
const netPeers=new Map();let netMode=false,netConnected=false,netState=null,netRound=-1,netSequence=0,netSendTime=0,netTarget=null;
function netClearActors(){for(const e of enemies)disposeSoldier(e);enemies.length=0;for(const c of corpses)disposeSoldier(c.e);corpses.length=0;for(const e of netPeers.values())disposeSoldier(e);netPeers.clear();for(const e of effects)e.mesh.dispose();effects.length=0;}
function netMenu(){if(!netMode){pause();return}clearInput();if(netConnected)netSend(true);if(state==='playing'){state='paused';$('screen').hidden=false;$('touch').hidden=true;$('screen-title').textContent='온라인 전투 메뉴';$('screen-desc').textContent='메뉴를 열어도 전투는 계속됩니다. 다시 돌아가 전투를 이어가세요.';start.textContent='전투로 돌아가기 →';if(document.pointerLockElement)document.exitPointerLock()}}
function netResume(){if(!netMode||netState?.phase!=='playing'||!netConnected||player.hp<=0)return;state='playing';clearInput();$('screen').hidden=true;$('hud').hidden=false;$('touch').hidden=!touch;audioStart();lock()}
function netInput(stopped=false){const moving=!stopped&&state==='playing'&&netConnected&&!controls.modalOpen&&!window.GameOnline.modalOpen;return{x:moving?((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+move.x):0,z:moving?((keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-move.y):0,yaw,pitch,sprint:moving&&keys.has('ShiftLeft'),aim:moving&&ads,fire:false,seq:++netSequence}}
function netSend(stopped=false){window.GameOnline.input(netInput(stopped))}
function netAction(action,data){if(state==='playing'&&netConnected)window.GameOnline.action(action,data)}
function netShot(){if(state!=='playing')return;const weapon=R.weapons[player.equipped],slot=player.weapons[player.equipped];if(shotTimer>0||reloading||!netConnected)return;if(!weapon){shotTimer=.5;return}if(weapon.melee){window.GameOnline.action('shoot',{yaw,pitch});shotTimer=weapon.interval;swingHands();beep(R.innate(player.equipped)?180:300,.09,.05,'square');return}if(!slot){shotTimer=.5;notify((touch?'획득 버튼':controls.keyLabel('collect'))+'으로 무기를 확보하세요',1);return}if(slot.ammo<=0){netAction('reload');shotTimer=.3;return}window.GameOnline.action('shoot',{yaw,pitch});shotTimer=weapon.interval;recoil=player.equipped==='marksman'?.075:.045;shotSound()}
function netSnapshot(s,id,events){
  netState=s;netSequence=Math.max(netSequence,s.me?.seq||0);netConnected=true;$('network-status').textContent='';const me=s.players.find(p=>p.id===id);if(!me||!s.me)return;
  if(s.round!==netRound&&s.phase!=='lobby'&&s.phase!=='countdown'){netClearActors();netRound=s.round;netSequence=s.me.seq||0;camera.position.set(me.x,1.7,me.z);yaw=me.yaw;pitch=me.pitch;camera.rotation.set(pitch,yaw,0);if(lobbySoldier){lobbySoldier.root.setEnabled(false);for(const a of lobbySoldier.animationGroups)a.stop()}$('hud').hidden=false;$('killfeed').textContent='';clearInput();}
  const oldHP=player.hp,oldWeapon=player.equipped;player={...s.me,weapons:JSON.parse(JSON.stringify(s.me.weapons))};time=s.time;zone=R.zoneAt(time);reloading=s.me.reload;healing=s.me.heal;netTarget={x:me.x,z:me.z};if(oldWeapon!==player.equipped)updateGun();if(player.hp<oldHP&&s.phase==='playing')damageFade=.7;
  if(s.phase==='playing'||s.phase==='finished'){
    const present=new Set();for(const p of s.players){if(p.id===id)continue;present.add(p.id);let e=netPeers.get(p.id);if(!e){e=makeSoldier('peer-'+p.id,p.x,p.z);e.bodyHit.isPickable=e.headHit.isPickable=false;e.netPosition=new V(p.x,0,p.z);e.netYaw=p.yaw;netPeers.set(p.id,e)}e.netPosition.set(p.x,0,p.z);e.netYaw=p.yaw;e.hp=p.hp;dressSoldier(e,p);if(p.hp<=0){for(const a of e.animationGroups)a.pause();e.root.rotation.x=-Math.PI/2;e.flash.setEnabled(false)}}
    for(const[id,e]of netPeers)if(!present.has(id)){disposeSoldier(e);netPeers.delete(id)}
    const remaining=new Map(s.loot.map(l=>[l.id,l]));for(let i=loot.length-1;i>=0;i--){const l=loot[i];if(!remaining.has(l.id)){l.root.dispose();loot.splice(i,1)}else remaining.delete(l.id)}for(const l of remaining.values()){const item=lootItem(l.type,l.x,l.z,l.weapon,l.amount);item.id=l.id}
    wall.scaling.set(Math.max(.001,zone.radius),1,Math.max(.001,zone.radius));zoneRing.scaling.set(zone.radius,1,zone.radius);nextRing.scaling.set(zone.target,1,zone.target);
    if(me.hp<=0&&s.phase==='playing'&&state!=='spectating'){state='spectating';clearInput();$('screen').hidden=false;$('touch').hidden=true;$('screen-title').textContent='탈락 · 경기는 계속됩니다';$('screen-desc').textContent=player.kills+'명 처치. 방 메뉴에서 다른 참가자의 결과를 확인하세요.';start.textContent='방 메뉴 열기 →';if(document.pointerLockElement)document.exitPointerLock()}
    if(s.phase==='finished'){state='finished';clearInput();$('touch').hidden=true;$('screen').hidden=false;const winner=s.players.find(p=>p.id===s.winner);$('screen-title').textContent=s.winner===id?'#1 최후의 생존자':'경기 종료';$('screen-desc').textContent=(winner?winner.name+' 승리':'생존자 없음')+' · '+player.kills+'명 처치';start.textContent='방 메뉴 열기 →';if(document.pointerLockElement)document.exitPointerLock()}
    searchLoot();ui();
  }
  for(const event of events){if(event.type==='shot'){if(!event.melee)trace(new V(event.from.x,event.from.y,event.from.z),new V(event.to.x,event.to.y,event.to.z),new C(1,.8,.35));const peer=netPeers.get(event.id);if(peer&&!event.melee){peer.flashTime=.1;peer.fireCount++;if(V.Distance(peer.root.position,camera.position)<35)shotSound(.045)}if(event.id===id&&event.hit){hitTimer=.15;$('hitmarker').style.color=event.head?'#ffad52':'#fff'}}if(event.type==='death')feed(event.killerName+' → '+event.name);if(event.type==='collect'&&event.id===id){notify('보급품 획득',1.3);beep(710,.08,.06)}}
}
function netTick(dt){
  for(const e of netPeers.values()){if(e.hp<=0)continue;const old=e.root.position.clone();e.root.position=V.Lerp(e.root.position,e.netPosition,Math.min(1,dt*12));const angle=Math.atan2(Math.sin(e.netYaw-e.root.rotation.y),Math.cos(e.netYaw-e.root.rotation.y));e.root.rotation.y+=angle*Math.min(1,dt*12);e.phase+=dt*8;modelAnimation(e,V.Distance(old,e.root.position)/Math.max(dt,.001)>.15?'Run':'Idle');e.flashTime=Math.max(0,e.flashTime-dt);e.flash.setEnabled(e.flashTime>0)}
  shotTimer=Math.max(0,shotTimer-dt);punchTimer=Math.max(0,punchTimer-dt);recoil=Math.max(0,recoil-dt*.55);damageFade=Math.max(0,damageFade-dt*1.8);hitTimer=Math.max(0,hitTimer-dt);noticeTimer-=dt;feedTimer-=dt;if(noticeTimer<=0)$('notice').textContent='';if(feedTimer<=0)$('killfeed').textContent='';$('damage').style.opacity=damageFade;$('hitmarker').style.opacity=hitTimer>0?1:0;muzzle.setEnabled(recoil>.025);
  if(state==='playing'&&netConnected){let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+move.x,mz=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-move.y;const len=Math.hypot(mx,mz);if(len>1){mx/=len;mz/=len}netMoving=len>.1;const speed=healing?1.8:ads?2.7:keys.has('ShiftLeft')?7:4.8;W.move(camera.position,(mx*Math.cos(yaw)+mz*Math.sin(yaw))*speed*dt,(-mx*Math.sin(yaw)+mz*Math.cos(yaw))*speed*dt);if(held)netShot();}
  if(netTarget&&netState?.phase==='playing'){const d=Math.hypot(camera.position.x-netTarget.x,camera.position.z-netTarget.z);const factor=d>2?1:Math.min(1,dt*5);camera.position.x+=(netTarget.x-camera.position.x)*factor;camera.position.z+=(netTarget.z-camera.position.z)*factor;}
  if(netState?.phase==='playing'||netState?.phase==='finished'){camera.position.y=1.7;camera.rotation.set(pitch-recoil*.2,yaw,0);camera.fov+=((ads&&!R.melee(player.equipped)?(player.equipped==='marksman'?.45:.7):1.08)-camera.fov)*Math.min(1,dt*12);gun.position.x+=((ads?0:.23)-gun.position.x)*Math.min(1,dt*12);gun.position.y=-.23-(reloading||healing?.16:0);gun.position.z=.48-recoil;gun.rotation.x=reloading?-.45:0;poseHands(netMoving);placeView(netMoving);$('zonewash').style.opacity=R.outsideZone(camera.position.x,camera.position.z,zone)?'.9':'0';}
  netSendTime-=dt;if(netSendTime<=0){netSendTime=.1;if(netConnected&&netState?.phase==='playing')netSend(state!=='playing')}
  for(let i=effects.length-1;i>=0;i--)if((effects[i].life-=dt)<=0){effects[i].mesh.dispose();effects.splice(i,1)}
}
window.GameOnline?.bind({ready:()=>charactersReady,menu:netMenu,resume:netResume,join(){netMode=true;netConnected=true;document.body.classList.add('online-mode');document.querySelector('.eyebrow').textContent='FRIENDS / BATTLE ROYALE';start.textContent='방 메뉴 열기 →';if(state==='ready')state='lobby'},connection(value){netConnected=value;$('network-status').textContent=value?'':'연결 복구 중 · 이동이 잠시 멈춥니다';if(!value)clearInput()},snapshot:netSnapshot,leave(){netClearActors();document.body.classList.remove('online-mode');document.querySelector('.eyebrow').textContent='SOLO / BATTLE ROYALE';netMode=false;netConnected=false;netState=null;netRound=-1;netTarget=null;state='ready';dropSelfBody();scene.activeCamera=camera;time=0;player=R.newPlayer();zone=R.zoneAt(0);clearInput();populateLoot();updateGun();$('hud').hidden=true;$('touch').hidden=true;$('screen').hidden=false;$('screen-title').textContent='파밍하고. 이동하고. 살아남아라.';$('screen-desc').textContent='친구와 방을 만들거나 혼자 전투를 연습하세요.';start.textContent='혼자 플레이 →';$('damage').style.opacity=$('zonewash').style.opacity=0;$('network-status').textContent=$('network-ping').textContent='';wall.scaling.set(78,1,78);zoneRing.scaling.set(78,1,78);nextRing.scaling.set(50,1,50);camera.position.set(-1,1.6,-56);camera.rotation.set(.04,.02,0);if(lobbySoldier){lobbySoldier.root.setEnabled(true);lobbySoldier.motion=null;modelAnimation(lobbySoldier,'Idle')}}});


wall.scaling.set(78,1,78);zoneRing.scaling.set(78,1,78);nextRing.scaling.set(50,1,50);
let last=performance.now();engine.runRenderLoop(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.05);last=now;try{tick(dt);scene.render()}catch(e){console.error(e);pause();startupFailure('게임 실행 오류가 발생했습니다. 새로고침해 주세요.',e);engine.stopRenderLoop()}});let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>engine.resize(),180);clearInput()});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();engine.stopRenderLoop();startupFailure('3D 화면이 중단됐습니다. 가벼운 모드로 다시 열어 주세요.')});
controls.connect({pause,changed(){touch=controls.isTouch();clearInput();inputMode();if(state==='playing'&&!controls.editing)$('touch').hidden=!touch;document.querySelector('.desktop-help').textContent='WASD 이동 · Shift 질주 · '+controls.keyLabel('collect')+' 파밍 · '+controls.keyLabel('reload')+' 재장전 · '+controls.keyLabel('heal')+' 치료 · '+controls.keyLabel('swap')+' 무기 교체 · '+controls.keyLabel('view')+' 시점 전환';ui();if(state==='playing')searchLoot()}});
// Read-only game state and the same pause action as the visible button.
const context=navigator.modelContext||document.modelContext;if(context?.registerTool){for(const tool of [{name:'read_battle_status',description:'현재 생존 상태와 자기장을 확인합니다.',annotations:{readOnlyHint:true},execute:()=>({state,hp:player.hp,helmet:player.helmet,vest:player.vest,weapon:player.equipped,reserve:player.reserve,kits:player.kits,kills:player.kills,alive:netMode&&netState?netState.players.filter(p=>p.hp>0).length:enemies.length+1,online:netMode,time,zone})},{name:'pause_battle',description:'전투 메뉴를 엽니다. 혼자 플레이만 일시정지되며 온라인 전투는 계속됩니다.',annotations:{readOnlyHint:false},execute:()=>{pause();return{state}}}])try{Promise.resolve(context.registerTool({...tool,inputSchema:{type:'object',properties:{},additionalProperties:false},execute:input=>{if(input&&Object.keys(input).length)throw Error('입력 항목이 없습니다.');return tool.execute()}})).catch(()=>{})}catch{}}
})();
