(function(){'use strict';
const $=id=>document.getElementById(id),dialog=$('online-dialog');
let bridge=null,socket=null,session=null,snapshot=null,intentional=false,connecting=false,retries=0,reconnectAt=0,retryTimer,pingTimer,lastEvent=0,previousPhase='',lastPacket=0;
function message(text){$('online-status').textContent=text}
function send(data){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(data))}
function saved(value){try{if(value)sessionStorage.setItem('last-field-session',JSON.stringify(value));else sessionStorage.removeItem('last-field-session')}catch{}}
function render(){const joined=!!session;$('online-entry').hidden=joined;$('online-room').hidden=!joined;$('online-leave').hidden=!joined;if(!snapshot)return;const me=snapshot.players.find(p=>p.id===session.id);$('room-code').textContent=session.room;$('room-players').replaceChildren(...snapshot.players.map(p=>{const li=document.createElement('li');const name=document.createElement('b');name.textContent=p.name+(p.id===session.id?' (나)':'');const status=document.createElement('span');status.textContent=!p.connected?'재접속 대기':snapshot.phase==='playing'?(p.hp>0?'생존':'탈락'):snapshot.phase==='finished'?(p.id===snapshot.winner?'우승':'탈락'):p.ready?'준비 완료':'준비 중';li.append(name,status);if(p.id===snapshot.host)li.dataset.host='true';return li}));$('room-count').textContent=snapshot.players.length+' / 8명';$('room-ready').hidden=snapshot.phase!=='lobby';$('room-ready').textContent=me?.ready?'준비 취소':'준비 완료';$('room-start').hidden=session.id!==snapshot.host||!['lobby','finished'].includes(snapshot.phase);$('room-start').disabled=snapshot.phase==='lobby'&&(snapshot.players.length<2||snapshot.players.some(p=>!p.ready||!p.connected));$('room-start').textContent=snapshot.phase==='finished'?'다음 경기 준비':'경기 시작';$('room-return').hidden=snapshot.phase!=='playing';$('room-phase').textContent=snapshot.phase==='countdown'?Math.ceil(snapshot.countdown)+'초 후 시작':snapshot.phase==='playing'?'전투 진행 중 · 메뉴를 열어도 경기는 계속됩니다':snapshot.phase==='finished'?(snapshot.players.find(p=>p.id===snapshot.winner)?.name||'생존자 없음')+' · 경기 종료':'모두 준비하면 방장이 시작할 수 있습니다';$('network-hud').hidden=false;$('network-hud').textContent='방 '+session.room+' · '+snapshot.players.length+'명';}
function open(){if(!bridge?.ready())return;bridge.menu();render();if(!dialog.open)dialog.showModal()}
function resume(){dialog.close();if(snapshot?.phase==='playing')bridge.resume();}
function clear(){session=null;snapshot=null;previousPhase='';lastEvent=0;connecting=false;clearTimeout(retryTimer);clearInterval(pingTimer);saved(null);$('network-hud').hidden=true;bridge?.leave();render();}
function leave(){intentional=true;send({type:'leave'});socket?.close(1000);clear();message('방에서 나왔습니다.');}
async function connect(kind,details){if(connecting)return;connecting=true;intentional=false;message(kind==='reconnect'?'연결 복구 중…':'경기 서버에 연결 중…');$('room-create').disabled=$('room-join').disabled=true;
  if(kind!=='reconnect'){try{const response=await fetch('api/health',{cache:'no-store',signal:AbortSignal.timeout(10000)});const health=await response.json();if(!response.ok||!health.ok)throw Error(health.message||'멀티플레이 서버 설정을 확인해 주세요.')}catch(e){connecting=false;$('room-create').disabled=$('room-join').disabled=false;message(e.name==='SyntaxError'?'이 주소는 싱글플레이 미리보기입니다. 멀티플레이 서버 주소에서 열어 주세요.':e.message);return}}
  const url=new URL('api/ws',location.href);url.protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(url.href);const ws=socket;let accepted=false,reportedError=false;
  ws.onopen=()=>send({type:kind,...details});
  ws.onmessage=event=>{let data;try{data=JSON.parse(event.data)}catch{return}if(ws!==socket)return;lastPacket=performance.now();
    if(data.type==='joined'){accepted=true;connecting=false;session={room:data.room,id:data.id,token:data.token};saved(session);retries=0;reconnectAt=0;bridge.join();bridge.connection(true);message('방에 연결됐습니다.');clearInterval(pingTimer);pingTimer=setInterval(()=>{send({type:'ping',at:Date.now()});if(performance.now()-lastPacket>7000){bridge.connection(false);ws.close()}},2000);render();return}
    if(data.type==='state'){snapshot=data.snapshot;const events=(data.events||[]).filter(e=>e.eventId>lastEvent);if(events.length)lastEvent=events.at(-1).eventId;bridge.snapshot(snapshot,session.id,events);render();if(snapshot.phase==='playing'&&previousPhase!=='playing'){dialog.close();bridge.resume()}if(snapshot.phase==='finished'&&previousPhase!=='finished')open();previousPhase=snapshot.phase;return}
    if(data.type==='error'){reportedError=true;message(data.message);if(!accepted&&kind==='reconnect'){intentional=true;clear();}return}
    if(data.type==='status'){message(data.message);bridge.connection(false);return}
    if(data.type==='pong')$('network-ping').textContent=Math.max(0,Date.now()-data.at)+' ms';
  };
  ws.onerror=()=>{if(!reportedError)message('실시간 연결에 실패했습니다. 서버 상태와 네트워크를 확인해 주세요.')};
  ws.onclose=event=>{if(ws!==socket)return;connecting=false;clearInterval(pingTimer);$('room-create').disabled=$('room-join').disabled=false;if(intentional)return;if(session&&![4003,4004].includes(event.code)){bridge.connection(false);if(!reconnectAt)reconnectAt=Date.now();if(Date.now()-reconnectAt<14000){message('연결이 끊겼습니다. 자동 재접속 중…');retryTimer=setTimeout(()=>connect('reconnect',session),Math.min(2500,500*2**retries++));return}}if(session){clear();message('연결이 종료됐습니다. 방에 다시 입장해 주세요.');if(!dialog.open)dialog.showModal()}else if(!reportedError)message('서버에 연결하지 못했습니다. 잠시 후 다시 시도해 주세요.');};
}
$('online-open').onclick=open;$('network-hud').onclick=open;$('online-close').onclick=resume;$('room-return').onclick=resume;
$('online-leave').onclick=leave;
$('room-create').onclick=()=>connect('create',{name:$('online-name').value.trim()||'생존자'});
$('room-join').onclick=()=>{const room=$('online-code').value.trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{6}$/.test(room)){message('초대 코드는 영문·숫자 6자리입니다.');return}connect('join',{room,name:$('online-name').value.trim()||'생존자'})};
$('room-ready').onclick=()=>send({type:'action',action:'ready',data:!snapshot?.players.find(p=>p.id===session?.id)?.ready});
$('room-start').onclick=()=>send({type:'action',action:snapshot?.phase==='finished'?'rematch':'start'});
$('room-copy').onclick=async()=>{if(!session)return;const url=new URL(location.href);url.searchParams.set('room',session.room);try{await navigator.clipboard.writeText(url.href);message('초대 링크를 복사했습니다. 친구에게 보내 주세요.')}catch{message('초대 코드 '+session.room+'를 친구에게 알려 주세요.')}};
dialog.addEventListener('cancel',()=>{if(snapshot?.phase==='playing')bridge.resume()});
window.GameOnline={bind(value){bridge=value},ready(){ $('online-open').disabled=false;const code=new URLSearchParams(location.search).get('room');if(code){$('online-code').value=code.slice(0,6).toUpperCase();open()}let prior;try{prior=JSON.parse(sessionStorage.getItem('last-field-session'))}catch{}if(prior?.room&&prior?.token&&prior?.id&&(!code||code.toUpperCase()===prior.room)){session=prior;open();connect('reconnect',prior)}},get active(){return!!session},get modalOpen(){return dialog.open},get connected(){return socket?.readyState===1&&!connecting},input(data){send({type:'input',data})},action(action,data){send({type:'action',action,data})},open,leave};
})();
