const test=require('node:test');const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const B=require('../vendor/babylon.js');
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../vendor/babylonjs.loaders.min.js'),'utf8'),{BABYLON:B,console,TextDecoder,TextEncoder,URL,Blob,AbortController,setTimeout,clearTimeout});
B.SceneLoader.OnPluginActivatedObservable.add(p=>{p.skipMaterials=true});
class TestEngine extends B.NullEngine{constructor(){super({renderWidth:1000,renderHeight:600,textureSize:512});this.getCaps().maxVertexUniformVectors=1024}runRenderLoop(cb){this.loop=cb}resize(){}}
const noop=()=>{},ctx=new Proxy({measureText:()=>({width:50})},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});
class TestImage extends B.Texture{constructor(name,scene){super(null,scene)}}
class TestTexture extends B.Texture{constructor(name,size,scene){super(null,scene)}getContext(){return ctx}update(){}}
const listeners={};function listen(type,fn){(listeners[type]??=[]).push(fn)};const els={};const element=id=>els[id]??={style:{},textContent:'',hidden:false,classList:{toggle:noop,add:noop,remove:noop},getContext:()=>ctx,querySelector:()=>element(id+'child'),addEventListener(type,fn){(this.events??={})[type]=fn},setPointerCapture(){throw Object.assign(Error('capturing under lock'),{name:'InvalidStateError'})},getBoundingClientRect:()=>({left:0,top:0,width:100,height:100})};
const bytes=new Uint8Array(fs.readFileSync(require('node:path').join(__dirname,'../assets/soldier.glb')));
const sandbox={console,Math,Map,Set,Float32Array,Int16Array,Uint8Array,performance:{now:()=>0},setTimeout,clearTimeout,window:{devicePixelRatio:1,BABYLON:true,BattleRules:require('../rules.js'),BattleWorld:require('../shared/world.js')},BABYLON:{...B,Engine:TestEngine,DynamicTexture:TestTexture,Texture:TestImage,SceneLoader:{LoadAssetContainerAsync:(_root,_name,scene)=>B.LoadAssetContainerAsync(bytes,scene,{pluginExtension:'.glb'})}},document:{getElementById:element,body:{classList:{toggle:noop,add:noop,remove:noop}},addEventListener:noop,querySelector:()=>element('desktop-help')},navigator:{},matchMedia:()=>({matches:true}),addEventListener:listen};
test('client gameplay survives pointer-lock shooting and mobile controls',async()=>{sandbox.window.createFieldEnvironment=()=>({materials:{},quality:noop,mapBox:noop,tree:noop,surface:()=>new B.StandardMaterial('fixture')});sandbox.window.GameControls={isTouch:()=>true,keyLabel:a=>({collect:'E',reload:'R',heal:'F',swap:'Q',view:'V'}[a]),code:a=>({collect:'KeyE',reload:'KeyR',heal:'KeyF',swap:'KeyQ',view:'KeyV'}[a]),connect:hooks=>hooks.changed()};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../loot-visuals.js'),'utf8'),sandbox);let src=fs.readFileSync(require('node:path').join(__dirname,'../game.js'),'utf8');src=src.replace('loadCharacters();','globalThis.characterLoading=loadCharacters();').replace(/\}\)\(\);\s*$/,'globalThis.api={run:code=>eval(code)};})();');vm.runInContext(src,sandbox);await sandbox.characterLoading;const run=sandbox.api.run;assert.equal(run('charactersReady'),true);assert.equal(run('highQuality'),false);assert.equal(run('scene.shadowsEnabled'),false);assert.equal(run('engine.getHardwareScalingLevel()'),1);run('resetRound();scene.render()');assert.equal(run('enemies.length'),12);assert.ok(run('enemies.every(e=>e.rig.Head&&e.rig.RightHand&&e.rig.LeftHand)'));assert.equal(run('new Set(enemies.map(e=>e.skeletons[0])).size'),12,'independent skeletons');assert.equal(run('Object.keys(enemies[0].animations).length'),3);
assert.equal(run("player.equipped"),'fists','everyone starts bare-handed');
// Bare hands must fight: swing at a bot standing within arm's reach.
run('enemies[0].root.position.set(0,0,-50);enemies[0].hp=100;enemies[0].armor=0;camera.position.set(0,1.7,-51.6);yaw=0;pitch=0;shotTimer=0;scene.render();shoot()');
assert.ok(run('enemies[0].hp<100'),'fists damage a bot in reach');assert.equal(run('player.reserve'),0,'fists consume no ammo');
run('globalThis.dented=enemies[0].hp;enemies[0].root.position.set(0,0,-20);shotTimer=0;camera.position.set(0,1.7,-51.6);scene.render();shoot()');
assert.equal(run('enemies[0].hp'),run('dented'),'a punch with nobody in reach lands on nothing');
// Randomised loot: find the carbine this round actually placed instead of assuming a fixed spot.
run("const g=loot.find(l=>l.type==='weapon'&&l.weapon==='carbine'&&!l.taken);camera.position.set(g.x,1.7,g.z);shotTimer=0;scene.render();collect();shoot()");
assert.equal(run('player.weapons.carbine.ammo'),29);assert.equal(run("player.equipped"),'carbine');
sandbox.document.pointerLockElement=element('world');run('touch=false;shotTimer=0');assert.doesNotThrow(()=>element('world').events.pointerdown({button:0,pointerId:1,clientX:50,clientY:50}));run('tick(.02)');for(const fn of listeners.pointerup||[])fn({button:0,pointerId:1});assert.equal(run('player.weapons.carbine.ammo'),28);assert.equal(run('held'),false);sandbox.document.pointerLockElement=null;run('touch=true');
run('player.reserve=60;reload();for(let i=0;i<41;i++){tick(.05);scene.render()}');assert.equal(run('player.weapons.carbine.ammo'),30);
// Hitboxes remain aligned with the animated head and register on an invisible collision mesh.
run('enemies[0].root.position.set(0,0,-40);enemies[0].root.rotation.y=Math.PI;scene.render()');assert.ok(run('enemies[0].headHit.position.y>1.45&&enemies[0].headHit.position.y<2'));
assert.equal(run('scene.pickWithRay(new B.Ray(new V(0,enemies[0].headHit.position.y,-44),new V(0,0,1),5),m=>m===enemies[0].headHit).hit'),true);
run('pause()');const old=run('time');run('tick(1);scene.render()');assert.equal(run('time'),old);run('resume();modelAnimation(enemies[0],"Run");scene.render()');assert.equal(run('enemies[0].motion'),'Run');
run('die(enemies[0],"player");scene.render()');assert.equal(run('corpses.length'),1);assert.equal(run('corpses[0].e.headHit.isPickable'),false);run('resetRound();scene.render()');assert.equal(run('corpses.length'),0);assert.equal(run('enemies.length'),12);assert.equal(run('scene.animationGroups.filter(a=>a.name.startsWith("bot")&& !a.name.startsWith("bot0_")).length'),48,'restart must not leak animation groups');
run('for(const e of [...enemies])die(e,"player")');assert.equal(run('state'),'won');assert.ok(run("loot.filter(l=>l.type==='med').every(l=>l.root.getChildMeshes().some(m=>m.name==='carry handle'))"));assert.ok(run("loot.filter(l=>l.type==='armor').every(l=>l.root.getChildMeshes().filter(m=>m.name==='shoulder strap').length===2)"));run("resetRound();scene.render();const m=loot.find(l=>l.type==='med'&&!l.taken);camera.position.set(m.x,1.7,m.z);scene.render();searchLoot();");element('pickup').onclick();assert.equal(run('player.kits'),1,'tap pickup card collects med');run("const v=loot.find(l=>l.type==='armor'&&!l.taken);camera.position.set(v.x,1.7,v.z);scene.render();searchLoot();");element('loot').onclick();assert.equal(run('player.armor'),100,'touch button collects armor');
// Third person must swap the rendering camera without moving the eye the shot ray comes from.
run('state="playing";ads=false;const eye=camera.position.clone();toggleView();placeView(false);');assert.equal(run('thirdPerson'),true);assert.equal(run('scene.activeCamera===viewCam'),true);assert.ok(run('V.Distance(viewCam.position,camera.position)>1'),'shoulder camera sits behind the eye');run('ads=true;placeView(false)');assert.equal(run('scene.activeCamera===camera'),true,'aiming snaps back to first person');run('ads=false;toggleView();placeView(false)');assert.equal(run('scene.activeCamera===camera'),true);run('scene.dispose();engine.dispose()');console.log('PASS: fists, randomised loot, third-person camera, actual GLB load, 12 independent skeletons, idle/walk/run clips, posed hands/head bounds, head hit detection, loot/fire/reload, pause, corpse cleanup, restart without animation leaks, win.');});
