const test=require('node:test'),assert=require('node:assert/strict'),R=require('../rules.js'),W=require('../shared/world.js'),{Battle}=require('../server/simulation.cjs');
const actor=()=>({...R.newPlayer(),x:0,z:-90,yaw:0});
const step=(p,input={},n=20)=>{for(let i=0;i<n;i++)W.stepMotion(p,input,.05)};
test('jump follows gravity, lands, and cannot be repeated in midair',()=>{const p=actor();assert.equal(W.jump(p),true);assert.equal(W.jump(p),false);step(p,{},6);assert.ok(p.feet>.8);assert.ok(W.eyeHeight(p)>2.5);step(p,{},20);assert.equal(p.feet,0);assert.equal(p.vy,0);assert.equal(p.grounded,true);assert.equal(W.jump(p),true)});
test('crouch and prone change eye height and movement speed, including sprint',()=>{for(const[stance,eye,speed]of [['stand',1.7,7],['crouch',1.05,2.25],['prone',.42,1.05]]){const p=actor();assert.equal(W.changeStance(p,stance),true);assert.equal(W.eyeHeight(p),eye);step(p,{x:1,sprint:true});assert.ok(Math.abs(p.x-speed)<.001,stance+' speed');assert.equal(W.changeStance(p,'stand'),true)}});
test('a low ceiling prevents standing and jumping; a jump hits the ceiling and lands',t=>{const p=actor(),ceiling={x:0,z:-90,y:1.5,w:2,d:2,h:.1,movement:false};W.colliders.push(ceiling);t.after(()=>W.colliders.splice(W.colliders.indexOf(ceiling),1));p.stance='crouch';assert.equal(W.changeStance(p,'stand'),false);assert.equal(W.jump(p),false);assert.equal(p.stance,'crouch');ceiling.y=2.4;p.stance='stand';assert.equal(W.jump(p),true);for(let i=0;i<20;i++){step(p,{},1);assert.ok(p.feet+1.85<=2.30001)}assert.equal(p.feet,0)});
test('landing on a crate and walking off preserves floor collision',t=>{const box={x:0,z:-90,y:.3,w:.5,d:.5,h:.3,movement:true};W.colliders.push(box);t.after(()=>W.colliders.splice(W.colliders.indexOf(box),1));const p=actor();p.feet=1.2;p.grounded=false;step(p,{},15);assert.equal(p.feet,.6);assert.equal(p.grounded,true);step(p,{x:1},20);assert.equal(p.feet,0);assert.equal(p.grounded,true);assert.ok(p.x>3)});
function battle(){const b=new Battle();b.add('a','A');b.add('b','B');b.startRound();const a=b.players.get('a'),q=b.players.get('b');Object.assign(a,actor());Object.assign(q,actor(),{z:-85});a.equipped='carbine';a.weapons.carbine={ammo:30};return{b,a,q}}
test('server validates motion actions and includes posture and height in restored snapshots',()=>{const{b,a}=battle();assert.equal(b.action('a','stance','flying'),false);assert.equal(b.action('a','stance','crouch'),true);assert.equal(b.snapshot('b').players.find(p=>p.id==='a').stance,'crouch');assert.equal(b.action('a','jump'),true);assert.equal(b.action('a','jump'),false);b.step(.05);assert.ok(a.feet>0);const s=b.snapshot('a');assert.equal(s.me.feet,a.feet);assert.equal(s.me.stance,'stand');const restored=Battle.restore(b.serialize());assert.deepEqual(restored.snapshot('a'),s);b.step(.05);restored.step(.05);assert.deepEqual(restored.snapshot('a'),b.snapshot('a'));});
test('server shoots from the current eye and respects crouched and prone hitboxes',()=>{for(const stance of ['crouch','prone']){const{b,a,q}=battle();b.action('b','stance',stance);a.pitch=0;b.shoot(a);assert.equal(q.hp,100,'a head-high shot passes above '+stance);a.cooldown=0;a.pitch=Math.atan2(W.eyeHeight(a)-W.eyeHeight(q),5);b.shoot(a);assert.ok(q.hp<100,'aiming lower hits '+stance);a.cooldown=0;W.changeStance(a,'crouch');b.shoot(a);assert.equal(b.events.filter(e=>e.type==='shot').at(-1).from.y,1.05)}});
test('posture-aware blast cover and grenade origin use the current height',()=>{const{b,a}=battle();b.action('a','stance','prone');a.flashes=1;assert.equal(b.action('a','throw',{kind:'flash',yaw:0,pitch:0}),true);assert.ok(b.grenades[0].y<.6);const low=W.blastExposure({x:0,z:-90,y:.3},a);assert.ok(low.distance<.2)});
