const test=require('node:test'),assert=require('node:assert/strict'),{WebSocket}=require('ws'),{createApp}=require('../server/app.cjs'),{MemoryStore}=require('../server/store.cjs');
function client(url){const ws=new WebSocket(url),messages=[],waiters=[];ws.on('message',raw=>{const msg=JSON.parse(raw);messages.push(msg);for(const w of [...waiters])if(w.test(msg)){clearTimeout(w.timer);waiters.splice(waiters.indexOf(w),1);w.resolve(msg)}});return{ws,opened:new Promise((res,rej)=>{ws.once('open',res);ws.once('error',rej)}),send:msg=>ws.send(JSON.stringify(msg)),wait(test){const prior=messages.find(test);if(prior)return Promise.resolve(prior);return new Promise((resolve,reject)=>{const w={test,resolve,timer:setTimeout(()=>reject(Error('network motion snapshot timeout')),5000)};waiters.push(w)})}}}
test('two sockets receive crouch, prone, airborne and landing state across game servers',async t=>{
 const store=new MemoryStore(),a=createApp({store,staticFiles:false}),b=createApp({store,staticFiles:false});for(const app of [a,b])await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(async()=>{for(const app of [a,b]){await app.transport.close();await new Promise(r=>app.server.close(r))}});
 const one=client('ws://127.0.0.1:'+a.server.address().port+'/api/ws'),two=client('ws://127.0.0.1:'+b.server.address().port+'/api/ws');await Promise.all([one.opened,two.opened]);one.send({type:'create',name:'Jumper'});const first=await one.wait(m=>m.type==='joined');two.send({type:'join',room:first.room,name:'Observer'});await two.wait(m=>m.type==='joined');await one.wait(m=>m.type==='state'&&m.snapshot.players.length===2);one.send({type:'action',action:'ready',data:true});two.send({type:'action',action:'ready',data:true});await one.wait(m=>m.type==='state'&&m.snapshot.players.every(p=>p.ready));one.send({type:'action',action:'start'});await two.wait(m=>m.type==='state'&&m.snapshot.phase==='playing');
 const state=(stance,air)=>m=>m.type==='state'&&m.snapshot.phase==='playing'&&m.snapshot.players.some(p=>p.id===first.id&&p.stance===stance&&(air===undefined||(air?p.feet>.05:p.grounded&&p.feet===0)));
 one.send({type:'action',action:'stance',data:'crouch'});await two.wait(state('crouch'));
 one.send({type:'action',action:'stance',data:'prone'});await two.wait(state('prone'));
 one.send({type:'action',action:'jump'});const airborne=await two.wait(state('stand',true));const landed=await two.wait(m=>state('stand',false)(m)&&m.snapshot.time>airborne.snapshot.time);assert.ok(landed.snapshot.time>airborne.snapshot.time);
});
