const test=require('node:test'),assert=require('node:assert/strict');
const {Battle}=require('../server/simulation.cjs'),W=require('../shared/world.js');
function game(){const b=new Battle();b.add('a','Alpha');b.add('b','Bravo');b.action('a','ready',true);b.action('b','ready',true);assert.equal(b.action('a','start'),true);for(let i=0;i<61;i++)b.step();return b}
test('lobby requires two ready players and only host can start',()=>{const b=new Battle();b.add('a','A');assert.equal(b.action('a','start'),false);b.add('b','B');b.action('a','ready',true);assert.equal(b.action('a','start'),false);b.action('b','ready',true);assert.equal(b.action('b','start'),false);assert.equal(b.action('a','start'),true);assert.throws(()=>b.add('c','C'));});
test('server caps movement, rejects NaN/replayed input, times out held input',()=>{const b=game(),p=b.players.get('a'),z=p.z;assert.equal(b.input('a',{x:0,z:999,yaw:0,pitch:0,seq:1}),true);b.step();assert.ok(p.z-z<=.241);assert.equal(b.input('a',{x:0,z:1,yaw:0,pitch:0,seq:1}),false);assert.equal(b.input('a',{x:NaN,z:1,yaw:0,pitch:0,seq:2}),false);for(let i=0;i<10;i++)b.step();const stop=p.z;b.step();assert.equal(p.z,stop);});
test('shared world blocks walls but permits doors and respects ray cover',()=>{assert.equal(W.blocked(-17,-40.5),false);assert.equal(W.blocked(-21,-40.5),true);assert.equal(W.visible({x:-21,y:1.7,z:-42},{x:-21,y:1.7,z:-39}),false);assert.equal(W.visible({x:-17,y:1.7,z:-42},{x:-17,y:1.7,z:-39}),true);});
test('loot is awarded once; distance and walls prevent remote collection',()=>{const b=game(),a=b.players.get('a'),c=b.players.get('b');b.loot=[{id:'one',type:'weapon',weapon:'carbine',x:0,z:0}];a.x=c.x=0;a.z=c.z=0;assert.equal(b.action('a','collect'),true);assert.equal(b.action('b','collect'),false);assert.equal(a.weapons.carbine.ammo,30);b.loot=[{id:'far',type:'med',x:30,z:0}];assert.equal(b.action('a','collect'),false);});
test('server shoots, limits fire rate, cancels healing, ends the match',()=>{const b=game(),a=b.players.get('a'),p=b.players.get('b');a.x=p.x=0;a.z=0;p.z=5;a.equipped='carbine';a.weapons.carbine={ammo:30};a.yaw=0;a.pitch=.05;p.heal=3;b.shoot(a);assert.equal(a.weapons.carbine.ammo,29);assert.ok(p.hp<100);assert.equal(p.heal,0);b.shoot(a);assert.equal(a.weapons.carbine.ammo,29);for(let i=0;i<10&&p.hp>0;i++){a.cooldown=0;b.shoot(a)}b.checkWinner();assert.equal(p.hp,0);assert.equal(a.kills,1);assert.equal(b.phase,'finished');assert.equal(b.winner,'a');});
test('cover stops authoritative hits; disconnected input stops and host changes',()=>{const b=game(),a=b.players.get('a'),p=b.players.get('b');a.x=p.x=-21;a.z=-42;p.z=-39;a.yaw=0;a.pitch=0;a.equipped='carbine';a.weapons.carbine={ammo:30};b.shoot(a);assert.equal(p.hp,100);b.setConnected('a',false);assert.equal(b.host,'b');assert.equal(b.input('a',{x:1,z:0,yaw:0,pitch:0,seq:1}),false);});
test('server completes reload and healing, applies shrinking zone damage',()=>{const b=game(),a=b.players.get('a');a.equipped='carbine';a.weapons.carbine={ammo:1};a.reserve=40;assert.equal(b.action('a','reload'),true);for(let i=0;i<40;i++)b.step();assert.equal(a.weapons.carbine.ammo,30);assert.equal(a.reserve,11);a.hp=20;a.kits=1;b.action('a','heal');for(let i=0;i<61;i++)b.step();assert.equal(a.hp,85);assert.equal(a.kits,0);b.time=240;a.x=60;a.z=0;a.armor=100;b.step();assert.ok(a.hp<85);assert.equal(a.armor,100);});
test('a round can move to another process without losing authoritative state',()=>{const a=game();a.action('a','collect');a.step();const b=Battle.restore(a.serialize());assert.deepEqual(b.snapshot('a'),a.snapshot('a'));a.step();b.step();assert.deepEqual(b.snapshot('a'),a.snapshot('a'));});
